/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/
import FinishTanTwoTheta.ApproximationNumber.GramSpectralRank
import FinishTanTwoTheta.ApproximationNumber.FinitePVMSelection
import ForTauCeti.Analysis.InnerProductSpace.PolarPartialIsometry
import Spectra.SpectralTheory.Eigenspace
import Spectra.SpectralTheory.Essential.Discrete

/-!
# Narrow Gram bands and the polar partial isometry

This file contains the analytic part of spectral selection.  Vectors in a
positive narrow spectral band for `X†X` lie in the polar initial space.  The
band width controls the Gram residual, and a positive Gram residual controls
the corresponding modulus residual.  The polar partial isometry then gives
both approximate singular equations.
-/

namespace TauCeti
namespace FinishTanTwoTheta

open scoped InnerProductSpace
open Set
open TauCeti.DavisKahan.Experimental.SpectraBridge
open Spectra.OneParameterUnitaryGroup
open Spectra.YosidaHille
open Spectra.QuantumMechanics.SpectralTheory

noncomputable section

universe u v

variable {E0 : Type u} [NormedAddCommGroup E0] [InnerProductSpace ℂ E0]
  [CompleteSpace E0]
variable {E1 : Type v} [NormedAddCommGroup E1] [InnerProductSpace ℂ E1]
  [CompleteSpace E1]

/-- The bounded self-adjoint operator object associated with `X†X`. -/
noncomputable def gramSelfAdjointOperator (X : E0 →L[ℂ] E1) :
    Spectra.Operator.SelfAdjointOperator E0 :=
  Spectra.Operator.SelfAdjointOperator.ofBounded
    (gramOperator X) (gramOperator_isSelfAdjoint X)

/-- The one-parameter group generated by `X†X`. -/
noncomputable def gramUnitaryGroup (X : E0 →L[ℂ] E1) :
    Spectra.OneParameterUnitaryGroup E0 :=
  genToGroup (gramSelfAdjointOperator X).selfAdjoint

/-- The spectral PVM of `X†X`. -/
noncomputable def gramPVM (X : E0 →L[ℂ] E1) : Spectra.ProjValMeasure E0 :=
  spectralPVM (gramSelfAdjointOperator X).selfAdjoint

/-- The Gram generator has full domain. -/
theorem gramUnitaryGroup_generator_domain (X : E0 →L[ℂ] E1) :
    (generator (gramUnitaryGroup X)).domain = ⊤ := by
  rw [gramUnitaryGroup, generator_genToGroup]
  exact Spectra.Operator.SelfAdjointOperator.domain_ofBounded
    (gramOperator X) (gramOperator_isSelfAdjoint X)

/-- The Gram generator acts as the bounded Gram operator. -/
theorem gramUnitaryGroup_generator_apply (X : E0 →L[ℂ] E1) (x : E0)
    (hx : x ∈ (generator (gramUnitaryGroup X)).domain) :
    generator (gramUnitaryGroup X) ⟨x, hx⟩ = gramOperator X x := by
  let A := gramSelfAdjointOperator X
  have hgen : generator (gramUnitaryGroup X) = A.toLinearPMap := by
    dsimp only [gramUnitaryGroup, A]
    exact generator_genToGroup (gramSelfAdjointOperator X).selfAdjoint
  have hAdom : A.toLinearPMap.domain = ⊤ := by
    dsimp only [A, gramSelfAdjointOperator]
    exact Spectra.Operator.SelfAdjointOperator.domain_ofBounded
      (gramOperator X) (gramOperator_isSelfAdjoint X)
  have hxA : x ∈ A.toLinearPMap.domain := by
    rw [hAdom]
    exact Submodule.mem_top
  calc
    generator (gramUnitaryGroup X) ⟨x, hx⟩ =
        A.toLinearPMap ⟨x, hxA⟩ :=
      (LinearPMap.ext_iff.mp hgen).2 (x := x) (hf := hx) (hg := hxA)
    _ = gramOperator X x := rfl

/-- A vector in a strictly positive Gram band is orthogonal to `ker X`, hence
belongs to the polar initial space. -/
theorem mem_polarInitial_of_mem_gramBand
    (X : E0 →L[ℂ] E1) {lo hi : ℝ} (hlo : 0 < lo)
    {x : E0}
    (hx : x ∈ pvmRangeSubspace (gramPVM X) (Set.Icc lo hi)
      measurableSet_Icc) :
    x ∈ X.polarInitial := by
  rw [← Submodule.orthogonal_orthogonal X.polarInitial,
    X.polarInitial_orthogonal_eq_ker]
  rw [Submodule.mem_orthogonal]
  intro z hz
  have hzX : X z = 0 := hz
  have hzGram : gramOperator X z = 0 := by
    unfold gramOperator
    rw [ContinuousLinearMap.comp_apply, hzX, map_zero]
  have hgramDomain :
      (gramSelfAdjointOperator X).toLinearPMap.domain = ⊤ := by
    dsimp only [gramSelfAdjointOperator]
    exact Spectra.Operator.SelfAdjointOperator.domain_ofBounded
      (gramOperator X) (gramOperator_isSelfAdjoint X)
  have hzDom : z ∈ (gramSelfAdjointOperator X).toLinearPMap.domain := by
    rw [hgramDomain]
    exact Submodule.mem_top
  have hzAtomFix :
      (gramPVM X).proj ({0} : Set ℝ) (measurableSet_singleton 0) z = z := by
    apply spectralPVM_proj_singleton_eq_self_of_eigen
      (gramSelfAdjointOperator X).selfAdjoint z hzDom
    change gramOperator X z = (0 : ℂ) • z
    simp only [hzGram, zero_smul]
  have hzAtom : z ∈ pvmRangeSubspace (gramPVM X) ({0} : Set ℝ)
      (measurableSet_singleton 0) :=
    (mem_pvmRangeSubspace_iff (gramPVM X) ({0} : Set ℝ)
      (measurableSet_singleton 0) z).2 hzAtomFix
  have hdisj : Disjoint (Set.Icc lo hi) ({0} : Set ℝ) := by
    rw [Set.disjoint_left]
    intro t ht hzero
    have ht0 : t = 0 := Set.mem_singleton_iff.mp hzero
    subst t
    exact (not_le_of_gt hlo) ht.1
  exact inner_eq_zero_of_mem_disjoint_pvmRanges (gramPVM X)
    (measurableSet_singleton 0) measurableSet_Icc hdisj.symm hzAtom hx

/-- Spectral localization in a narrow Gram band. -/
theorem gram_residual_le_of_mem_band
    (X : E0 →L[ℂ] E1) {lam η ε : ℝ}
    (hη0 : 0 < η) (hηlam : η < lam) (hηε : η < ε / 16)
    {x : E0} (hxnorm : ‖x‖ = 1)
    (hx : x ∈ pvmRangeSubspace (gramPVM X)
      (Set.Icc ((lam - η) ^ 2) ((lam + η) ^ 2)) measurableSet_Icc) :
    ‖gramOperator X x - ((lam ^ 2 : ℝ) : ℂ) • x‖ ≤ ε * lam / 4 := by
  have hlo : (lam - η) ^ 2 ≤ lam ^ 2 := by nlinarith
  have hhi : lam ^ 2 ≤ (lam + η) ^ 2 := by nlinarith
  have hxfix :
      (gramPVM X).proj
        (Set.Icc ((lam - η) ^ 2) ((lam + η) ^ 2)) measurableSet_Icc x = x :=
    pvmProjection_eq_self_of_mem_rangeSubspace (gramPVM X) _ _ hx
  have hxDom : x ∈ (generator (gramUnitaryGroup X)).domain := by
    rw [gramUnitaryGroup_generator_domain X]
    exact Submodule.mem_top
  have hprojDom :
      Spectra.QuantumMechanics.SpectralTheory.spectralProjection (gramUnitaryGroup X)
          (Set.Icc ((lam - η) ^ 2) ((lam + η) ^ 2)) measurableSet_Icc x ∈
        (generator (gramUnitaryGroup X)).domain := by
    rw [gramUnitaryGroup_generator_domain X]
    exact Submodule.mem_top
  have hloc := generator_sub_smul_norm_le_Icc
    (gramUnitaryGroup X) ((lam - η) ^ 2) ((lam + η) ^ 2) (lam ^ 2)
    hlo hhi x hprojDom
  have hfix :
      Spectra.QuantumMechanics.SpectralTheory.spectralProjection (gramUnitaryGroup X)
        (Set.Icc ((lam - η) ^ 2) ((lam + η) ^ 2)) measurableSet_Icc x = x := by
    simpa [gramUnitaryGroup, gramPVM] using hxfix
  have hdomEq :
      (⟨Spectra.QuantumMechanics.SpectralTheory.spectralProjection (gramUnitaryGroup X)
          (Set.Icc ((lam - η) ^ 2) ((lam + η) ^ 2)) measurableSet_Icc x,
          hprojDom⟩ : (generator (gramUnitaryGroup X)).domain) =
        ⟨x, hxDom⟩ := Subtype.ext hfix
  rw [hdomEq, hfix, gramUnitaryGroup_generator_apply X x hxDom, hxnorm, mul_one] at hloc
  have hleft : lam ^ 2 - (lam - η) ^ 2 ≤ 3 * lam * η := by nlinarith
  have hright : (lam + η) ^ 2 - lam ^ 2 ≤ 3 * lam * η := by nlinarith
  have hmax :
      max (lam ^ 2 - (lam - η) ^ 2) ((lam + η) ^ 2 - lam ^ 2) ≤
        3 * lam * η := max_le hleft hright
  calc
    ‖gramOperator X x - ((lam ^ 2 : ℝ) : ℂ) • x‖
        ≤ max (lam ^ 2 - (lam - η) ^ 2) ((lam + η) ^ 2 - lam ^ 2) := hloc
    _ ≤ 3 * lam * η := hmax
    _ ≤ ε * lam / 4 := by
      have hlam0 : 0 < lam := hη0.trans hηlam
      nlinarith

/-- The polar partial isometry is norm non-increasing on the whole source. -/
theorem norm_polarPartial_apply_le (X : E0 →L[ℂ] E1) (x : E0) :
    ‖X.polarPartial x‖ ≤ ‖x‖ := by
  rw [X.polarPartial_apply, X.norm_polarPartialAux_apply]
  exact X.polarInitial.norm_orthogonalProjectionOnto_apply_le x

/-- A positive Gram residual bounds the corresponding modulus residual. -/
theorem modulus_residual_le_of_gram_residual
    (X : E0 →L[ℂ] E1) {x : E0} {lam δ : ℝ}
    (hlam : 0 < lam) (hδ : 0 ≤ δ)
    (hgram :
      ‖gramOperator X x - ((lam ^ 2 : ℝ) : ℂ) • x‖ ≤ δ * lam) :
    ‖X.modulus x - (lam : ℂ) • x‖ ≤ δ := by
  let w : E0 := X.modulus x - (lam : ℂ) • x
  by_cases hw : w = 0
  · simp only [w, hw, norm_zero, hδ]
  have hwpos : 0 < ‖w‖ := norm_pos_iff.mpr hw
  have hmodpos : 0 ≤ RCLike.re ⟪X.modulus w, w⟫_ℂ :=
    ((ContinuousLinearMap.nonneg_iff_isPositive X.modulus).mp X.modulus_nonneg).2 w
  have hfactor :
      X.modulus w + (lam : ℂ) • w =
        gramOperator X x - ((lam ^ 2 : ℝ) : ℂ) • x := by
    have hsquare : X.modulus (X.modulus x) = X.adjoint (X x) := by
      change (X.modulus * X.modulus) x = (X.adjoint ∘L X) x
      rw [X.modulus_mul_self]
    have hlamSq : ((lam ^ 2 : ℝ) : ℂ) = (lam : ℂ) * (lam : ℂ) := by
      norm_num [pow_two]
    calc
      X.modulus w + (lam : ℂ) • w =
          X.modulus (X.modulus x) - (lam : ℂ) • X.modulus x +
            ((lam : ℂ) • X.modulus x -
              ((lam : ℂ) * (lam : ℂ)) • x) := by
        unfold w
        rw [map_sub, map_smul, smul_sub, smul_smul]
      _ = X.adjoint (X x) - ((lam : ℂ) * (lam : ℂ)) • x := by
        rw [hsquare]
        abel_nf
      _ = gramOperator X x - ((lam ^ 2 : ℝ) : ℂ) • x := by
        unfold gramOperator
        rw [ContinuousLinearMap.comp_apply, hlamSq]
  have hscalar :
      RCLike.re ⟪(lam : ℂ) • w, w⟫_ℂ = lam * ‖w‖ ^ 2 := by
    rw [inner_smul_left, inner_self_eq_norm_sq_to_K]
    simp [← Complex.ofReal_pow]
  have hlower :
      lam * ‖w‖ ^ 2 ≤
        RCLike.re ⟪X.modulus w + (lam : ℂ) • w, w⟫_ℂ := by
    calc
      lam * ‖w‖ ^ 2 ≤
          RCLike.re ⟪X.modulus w, w⟫_ℂ + lam * ‖w‖ ^ 2 :=
        le_add_of_nonneg_left hmodpos
      _ = RCLike.re ⟪X.modulus w + (lam : ℂ) • w, w⟫_ℂ := by
        rw [inner_add_left, map_add, hscalar]
  have hcauchy :
      RCLike.re ⟪X.modulus w + (lam : ℂ) • w, w⟫_ℂ ≤
        ‖X.modulus w + (lam : ℂ) • w‖ * ‖w‖ := by
    exact (RCLike.re_le_norm _).trans (norm_inner_le_norm _ _)
  have hgramMul :
      ‖gramOperator X x - ((lam ^ 2 : ℝ) : ℂ) • x‖ * ‖w‖ ≤
        (δ * lam) * ‖w‖ :=
    mul_le_mul_of_nonneg_right hgram (norm_nonneg w)
  rw [hfactor] at hlower hcauchy
  have hmain := hlower.trans (hcauchy.trans hgramMul)
  have hcancel :
      (lam * ‖w‖) * ‖w‖ ≤ (lam * ‖w‖) * δ := by
    simpa [pow_two, mul_assoc, mul_left_comm, mul_comm] using hmain
  have hwle : ‖w‖ ≤ δ :=
    le_of_mul_le_mul_left hcancel (mul_pos hlam hwpos)
  simpa only [w] using hwle

end

end FinishTanTwoTheta
end TauCeti
