/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, Claude Opus 5
Adapted from: Spectra (https://github.com/adambornemann-glitch/Spectra),
  `Spectra/YosidaHille/Approximation/{Helpers,Defs}.lean` at commit
  `8dbaaf6728d1342ae16acf79fd7eef7c59b37e63`,
  Copyright (c) 2026 Spectra Formalization Project, `Authors: Adam Bornemann`,
  Apache 2.0.  Modified: see `## Provenance` (Apache 2.0 §4(b)); the donor's
  copyright and authorship notices are retained here and below (§4(c)).
-/
module

public import ForTauCeti.Analysis.InnerProductSpace.LinearPMap.SelfAdjointResolvent
public import Mathlib.Analysis.Complex.Norm
public import Mathlib.Data.PNat.Basic

/-!
# The Yosida approximation of a self-adjoint operator

The bounded approximants used to build the unitary group generated by a
self-adjoint operator (Stone's theorem):

* `resolventAtIn A n = R(in)`, `resolventAtNegIn A n = R(-in)`;
* `yosidaApprox A n = n² R(in) - in`, the Yosida approximant;
* `yosidaApproxSym A n = (n²/2)(R(in) + R(-in))`, its symmetric form.

## Provenance

* **Original repository:** Spectra, commit `8dbaaf6728d1342ae16acf79fd7eef7c59b37e63`.
* **Original modules:** `Spectra/YosidaHille/Approximation/Helpers.lean` (the
  arithmetic of `I * n`) and `Spectra/YosidaHille/Approximation/Defs.lean`
  (`resolventAtIn`, `resolventAtNegIn`, `yosidaApprox`, `yosidaApproxSym`).
* **Original authors / copyright / licence:** Copyright (c) 2026 Spectra
  Formalization Project; `Authors: Adam Bornemann`; Apache 2.0.
* **Extraction class:** *adapted.*  The definitions are Spectra's; the arithmetic
  lemmas are transcribed; the hypothesis interface is changed — see below.
* **Semantic difference from the donor — one hypothesis instead of three.**
  Spectra threads `(hsym, hplus, hminus)` — formal self-adjointness plus `±i`
  deficiency-surjectivity — through every one of these definitions, because its
  resolvent is constructed from exactly those three inputs.  Here they collapse
  to a single `IsSelfAdjoint A`, because
  `TauCeti.LinearPMap.mem_resolventSet_of_im_ne_zero` (proved in
  `SelfAdjointResolvent.lean`) derives resolvent-set membership at *any* non-real
  point directly from self-adjointness.  That also removes the dependency on
  Spectra's `Resolvent/Range.lean` entirely.
-/

@[expose] public section

namespace TauCeti
namespace LinearPMap

open Complex
open scoped InnerProductSpace

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-! ### Arithmetic of `I * n` for `n : ℕ+` -/

/-- `I * n` lies off the real axis, so the resolvent is defined there. -/
theorem I_mul_pnat_im_ne_zero (n : ℕ+) : (I * (n : ℂ)).im ≠ 0 := by
  simp only [mul_im, I_re, I_im, zero_mul, one_mul, zero_add]
  exact Nat.cast_ne_zero.mpr n.ne_zero

/-- `-I * n` lies off the real axis. -/
theorem neg_I_mul_pnat_im_ne_zero (n : ℕ+) : (-I * (n : ℂ)).im ≠ 0 := by
  simp only [neg_mul, neg_im]
  exact neg_ne_zero.mpr (I_mul_pnat_im_ne_zero n)

theorem I_mul_pnat_im (n : ℕ+) : (I * (n : ℂ)).im = (n : ℝ) := by
  simp [mul_im]

theorem abs_I_mul_pnat_im (n : ℕ+) : |(I * (n : ℂ)).im| = (n : ℝ) := by
  rw [I_mul_pnat_im]
  exact abs_of_pos (Nat.cast_pos.mpr n.pos)

theorem norm_pnat_sq (n : ℕ+) : ‖((n : ℂ) ^ 2)‖ = (n : ℝ) ^ 2 := by
  rw [Complex.norm_pow, Complex.norm_natCast]

theorem norm_I_mul_pnat (n : ℕ+) : ‖I * (n : ℂ)‖ = (n : ℝ) := by
  rw [Complex.norm_mul, Complex.norm_I, one_mul, Complex.norm_natCast]

/-! ### The resolvent at `±in` -/

variable {A : H →ₗ.[ℂ] H}

/-- The resolvent at `z = in`. -/
noncomputable def resolventAtIn (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  resolvent A (mem_resolventSet_of_im_ne_zero hA (I_mul_pnat_im_ne_zero n))

/-- The resolvent at `z = -in`. -/
noncomputable def resolventAtNegIn (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  resolvent A (mem_resolventSet_of_im_ne_zero hA (neg_I_mul_pnat_im_ne_zero n))

/-- `‖R(in)‖ ≤ 1/n`. -/
theorem norm_resolventAtIn_le (hA : IsSelfAdjoint A) (n : ℕ+) :
    ‖resolventAtIn hA n‖ ≤ ((n : ℝ))⁻¹ := by
  have h := norm_resolvent_le_of_im_ne_zero hA (I_mul_pnat_im_ne_zero n)
  rwa [abs_I_mul_pnat_im] at h

/-- `‖R(-in)‖ ≤ 1/n`. -/
theorem norm_resolventAtNegIn_le (hA : IsSelfAdjoint A) (n : ℕ+) :
    ‖resolventAtNegIn hA n‖ ≤ ((n : ℝ))⁻¹ := by
  have h := norm_resolvent_le_of_im_ne_zero hA (neg_I_mul_pnat_im_ne_zero n)
  have habs : |(-I * (n : ℂ)).im| = (n : ℝ) := by
    simp only [neg_mul, neg_im, abs_neg]
    exact abs_I_mul_pnat_im n
  rwa [habs] at h

/-! ### The Yosida approximants -/

/-- The Yosida approximant `Aₙ = n² R(in) - in`. -/
noncomputable def yosidaApprox (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  (n : ℂ) ^ 2 • resolventAtIn hA n - (I * (n : ℂ)) • ContinuousLinearMap.id ℂ H

/-- The symmetric Yosida approximant `(n²/2)(R(in) + R(-in))`. -/
noncomputable def yosidaApproxSym (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  ((n : ℂ) ^ 2 / 2) • (resolventAtIn hA n + resolventAtNegIn hA n)

/-- The contraction `Jₙ = -in·R(in)`. -/
noncomputable def yosidaJ (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  (-I * (n : ℂ)) • resolventAtIn hA n

/-- The contraction `Jₙ⁻ = in·R(-in)`. -/
noncomputable def yosidaJNeg (hA : IsSelfAdjoint A) (n : ℕ+) : H →L[ℂ] H :=
  (I * (n : ℂ)) • resolventAtNegIn hA n

/-! ### Adjoints: the two resolvents are each other's -/

/-- `R(in)⋆ = R(-in)`. -/
theorem adjoint_resolventAtIn (hA : IsSelfAdjoint A) (n : ℕ+) :
    ContinuousLinearMap.adjoint (resolventAtIn hA n) = resolventAtNegIn hA n := by
  have hsym : A.IsFormalAdjoint A := by
    have h := _root_.LinearPMap.adjoint_isFormalAdjoint (T := A) hA.dense_domain
    rwa [_root_.LinearPMap.isSelfAdjoint_def.mp hA] at h
  symm
  rw [ContinuousLinearMap.eq_adjoint_iff]
  intro x y
  set hin := mem_resolventSet_of_im_ne_zero hA (I_mul_pnat_im_ne_zero n) with hin_def
  set hnin := mem_resolventSet_of_im_ne_zero hA (neg_I_mul_pnat_im_ne_zero n) with hnin_def
  set u : A.domain := ⟨resolvent A hnin x, resolvent_mem_domain hnin x⟩ with hu
  set v : A.domain := ⟨resolvent A hin y, resolvent_mem_domain hin y⟩ with hv
  have hux : A u - (-I * (n : ℂ)) • (u : H) = x := sub_smul_resolvent hnin x
  have hvy : A v - (I * (n : ℂ)) • (v : H) = y := sub_smul_resolvent hin y
  have hconj : (starRingEnd ℂ) (-I * (n : ℂ)) = I * (n : ℂ) := by
    rw [map_mul, map_neg, Complex.conj_I, Complex.conj_natCast, neg_neg]
  calc ⟪resolventAtNegIn hA n x, y⟫_ℂ
      = ⟪(u : H), A v - (I * (n : ℂ)) • (v : H)⟫_ℂ := by rw [hvy]; rfl
    _ = ⟪A u - (-I * (n : ℂ)) • (u : H), (v : H)⟫_ℂ := by
        rw [inner_sub_left, inner_sub_right, inner_smul_left, inner_smul_right,
          hconj, hsym u v]
    _ = ⟪x, resolventAtIn hA n y⟫_ℂ := by rw [hux]; rfl

/-- `R(-in)⋆ = R(in)`. -/
theorem adjoint_resolventAtNegIn (hA : IsSelfAdjoint A) (n : ℕ+) :
    ContinuousLinearMap.adjoint (resolventAtNegIn hA n) = resolventAtIn hA n := by
  rw [← adjoint_resolventAtIn hA n, ContinuousLinearMap.adjoint_adjoint]

/-- **The symmetric Yosida approximant is self-adjoint.**  It is the `n²/2`-weighted
average of two resolvents that are each other's adjoint. -/
theorem isSelfAdjoint_yosidaApproxSym (hA : IsSelfAdjoint A) (n : ℕ+) :
    _root_.IsSelfAdjoint (yosidaApproxSym hA n) := by
  rw [ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric]
  intro x y
  have hscalar : (starRingEnd ℂ) ((n : ℂ) ^ 2 / 2) = (n : ℂ) ^ 2 / 2 := by
    rw [map_div₀, map_pow, Complex.conj_natCast, map_ofNat]
  have hIn : ⟪resolventAtIn hA n x, y⟫_ℂ = ⟪x, resolventAtNegIn hA n y⟫_ℂ := by
    rw [← adjoint_resolventAtIn hA n, ContinuousLinearMap.adjoint_inner_right]
  have hNIn : ⟪resolventAtNegIn hA n x, y⟫_ℂ = ⟪x, resolventAtIn hA n y⟫_ℂ := by
    rw [← adjoint_resolventAtNegIn hA n, ContinuousLinearMap.adjoint_inner_right]
  change ⟪yosidaApproxSym hA n x, y⟫_ℂ = ⟪x, yosidaApproxSym hA n y⟫_ℂ
  unfold yosidaApproxSym
  simp only [smul_apply, add_apply, inner_smul_left, inner_smul_right,
    inner_add_left, inner_add_right, hscalar]
  rw [hIn, hNIn]
  ring

/-! ### Norm bounds -/

/-- `‖Aₙ‖ ≤ 2n`. -/
theorem norm_yosidaApprox_le (hA : IsSelfAdjoint A) (n : ℕ+) :
    ‖yosidaApprox hA n‖ ≤ 2 * (n : ℝ) := by
  have hfirst : ‖(n : ℂ) ^ 2 • resolventAtIn hA n‖ ≤ (n : ℝ) := by
    calc ‖(n : ℂ) ^ 2 • resolventAtIn hA n‖
        = ‖((n : ℂ) ^ 2)‖ * ‖resolventAtIn hA n‖ := norm_smul _ _
      _ ≤ ‖((n : ℂ) ^ 2)‖ * ((n : ℝ))⁻¹ :=
          mul_le_mul_of_nonneg_left (norm_resolventAtIn_le hA n) (norm_nonneg _)
      _ = (n : ℝ) ^ 2 * ((n : ℝ))⁻¹ := by rw [norm_pnat_sq]
      _ = (n : ℝ) := by
          have : (n : ℝ) ≠ 0 := ne_of_gt (Nat.cast_pos.mpr n.pos)
          field_simp
  have hsecond : ‖(I * (n : ℂ)) • ContinuousLinearMap.id ℂ H‖ ≤ (n : ℝ) := by
    calc ‖(I * (n : ℂ)) • ContinuousLinearMap.id ℂ H‖
        = ‖I * (n : ℂ)‖ * ‖ContinuousLinearMap.id ℂ H‖ := norm_smul _ _
      _ ≤ ‖I * (n : ℂ)‖ * 1 :=
          mul_le_mul_of_nonneg_left ContinuousLinearMap.norm_id_le (norm_nonneg _)
      _ = (n : ℝ) := by rw [mul_one, norm_I_mul_pnat]
  calc ‖yosidaApprox hA n‖
      ≤ ‖(n : ℂ) ^ 2 • resolventAtIn hA n‖
          + ‖(I * (n : ℂ)) • ContinuousLinearMap.id ℂ H‖ := norm_sub_le _ _
    _ ≤ (n : ℝ) + (n : ℝ) := add_le_add hfirst hsecond
    _ = 2 * (n : ℝ) := by ring

/-- `‖Jₙ‖ ≤ 1`. -/
theorem norm_yosidaJ_le (hA : IsSelfAdjoint A) (n : ℕ+) : ‖yosidaJ hA n‖ ≤ 1 := by
  have hn : (0 : ℝ) < (n : ℝ) := Nat.cast_pos.mpr n.pos
  have hcoeff : ‖(-I * (n : ℂ))‖ = (n : ℝ) := by
    rw [neg_mul, norm_neg, norm_I_mul_pnat]
  calc ‖yosidaJ hA n‖
      = ‖(-I * (n : ℂ))‖ * ‖resolventAtIn hA n‖ := norm_smul _ _
    _ = (n : ℝ) * ‖resolventAtIn hA n‖ := by rw [hcoeff]
    _ ≤ (n : ℝ) * ((n : ℝ))⁻¹ :=
        mul_le_mul_of_nonneg_left (norm_resolventAtIn_le hA n) hn.le
    _ = 1 := by field_simp

/-- `‖Jₙ⁻‖ ≤ 1`. -/
theorem norm_yosidaJNeg_le (hA : IsSelfAdjoint A) (n : ℕ+) : ‖yosidaJNeg hA n‖ ≤ 1 := by
  have hn : (0 : ℝ) < (n : ℝ) := Nat.cast_pos.mpr n.pos
  calc ‖yosidaJNeg hA n‖
      = ‖I * (n : ℂ)‖ * ‖resolventAtNegIn hA n‖ := norm_smul _ _
    _ = (n : ℝ) * ‖resolventAtNegIn hA n‖ := by rw [norm_I_mul_pnat]
    _ ≤ (n : ℝ) * ((n : ℝ))⁻¹ :=
        mul_le_mul_of_nonneg_left (norm_resolventAtNegIn_le hA n) hn.le
    _ = 1 := by field_simp

end LinearPMap
end TauCeti
