import DavisKahan.Analysis.FourthOrderODE.SmoothGreenIdentity
import DavisKahan.Analysis.FourthOrderODE.ComplexGreenIdentity
import DavisKahan.Analysis.FourthOrderODE.SmoothKernel
import DavisKahan.Experimental.MathAhead.HiddenFoundations.FreeBeam.HardTheoryAll
