/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/

import Spectra.QuantumMechanics.Channels.TraceClass.PartialIsometry

/-!
# Final-space identities for the bounded polar isometry

Spectra currently proves the initial projection identity
`U* U = P_(closure range |T|)`.  Nonacute direct rotations also need the
symmetric final projection identity
`U U* = P_(closure range T)`.  The argument below identifies the range of the
polar partial isometry with the closed range generated by `T`, then invokes
orthogonal-projection uniqueness.
-/

open scoped InnerProductSpace InnerProduct

namespace Spectra
namespace QuantumMechanics
namespace Channels

noncomputable section

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H]

/-- The final space in the bounded polar decomposition. -/
noncomputable def polarFinalRange (T : H →L[ℂ] H) : Submodule ℂ H :=
  (LinearMap.range T.toLinearMap).topologicalClosure

noncomputable instance polarFinalRange_hasOrthogonalProjection (T : H →L[ℂ] H) :
    (polarFinalRange T).HasOrthogonalProjection := by
  letI : CompleteSpace (polarFinalRange T) :=
    (Submodule.isClosed_topologicalClosure
      (LinearMap.range T.toLinearMap)).completeSpace_coe
  exact Submodule.HasOrthogonalProjection.ofCompleteSpace (polarFinalRange T)

/-- The range of the polar partial isometry lies in the final polar space. -/
theorem polarPartial_mem_finalRange (T : H →L[ℂ] H)
    (x : polarRange T) : polarPartial T x ∈ polarFinalRange T := by
  have hdense : DenseRange (absOpCorestrict T) := denseRange_absOpCorestrict T
  have hFinalClosed : IsClosed (↑(polarFinalRange T) : Set H) :=
    Submodule.isClosed_topologicalClosure (LinearMap.range T.toLinearMap)
  have hclosed : IsClosed {x : polarRange T |
      polarPartial T x ∈ polarFinalRange T} :=
    hFinalClosed.preimage (polarPartial T).continuous
  have hsub : Set.range (absOpCorestrict T) ⊆
      {x : polarRange T | polarPartial T x ∈ polarFinalRange T} := by
    rintro _ ⟨w, rfl⟩
    show polarPartial T (absOpCorestrict T w) ∈ polarFinalRange T
    rw [polarPartial_absOpCorestrict]
    exact Submodule.le_topologicalClosure _
      (LinearMap.mem_range_self T.toLinearMap w)
  have hcs : closure (Set.range (absOpCorestrict T)) ⊆
      {x : polarRange T | polarPartial T x ∈ polarFinalRange T} :=
    (hclosed.closure_subset_iff).mpr hsub
  rw [hdense.closure_range] at hcs
  exact hcs (Set.mem_univ x)

/-- The range of the polar partial isometry is dense in the final polar space. -/
theorem denseRange_polarPartial_final (T : H →L[ℂ] H) :
    DenseRange
      ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)) := by
  rw [DenseRange, dense_iff_closure_eq]
  apply Set.Subset.antisymm
  · exact Set.subset_univ _
  · intro y hy
    have hyAmbient : (y : H) ∈ closure (Set.range T) := by
      simpa [polarFinalRange, Submodule.topologicalClosure_coe,
        LinearMap.coe_range] using y.property
    have himage : Set.range T ⊆
        ((fun z : polarFinalRange T => (z : H)) ''
          Set.range ((polarPartial T).codRestrict (polarFinalRange T)
            (polarPartial_mem_finalRange T))) := by
      intro z hz
      rcases hz with ⟨x, rfl⟩
      refine ⟨⟨T x, Submodule.le_topologicalClosure _
        (LinearMap.mem_range_self T.toLinearMap x)⟩, ?_, rfl⟩
      refine ⟨absOpCorestrict T x, ?_⟩
      apply Subtype.ext
      exact polarPartial_absOpCorestrict T x
    have hclosedEmbedding : Topology.IsClosedEmbedding
        ((fun z : polarFinalRange T => (z : H))) :=
      (Submodule.isClosed_topologicalClosure
          (LinearMap.range T.toLinearMap)).isClosedEmbedding_subtypeVal
    have hyImage : (y : H) ∈ closure
        (((fun z : polarFinalRange T => (z : H)) ''
          Set.range ((polarPartial T).codRestrict (polarFinalRange T)
            (polarPartial_mem_finalRange T)))) :=
      closure_mono himage hyAmbient
    rw [hclosedEmbedding.closure_image_eq] at hyImage
    rcases hyImage with ⟨z, hz, hzy⟩
    rwa [Subtype.ext hzy] at hz

/-- The polar partial isometry, restricted to its final space, is onto. -/
theorem polarPartial_final_surjective (T : H →L[ℂ] H) :
    Function.Surjective
      ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)) := by
  let W : polarRange T →ₗᵢ[ℂ] polarFinalRange T :=
    { toLinearMap := ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)).toLinearMap
      norm_map' := fun x => by
        change ‖polarPartial T x‖ = ‖x‖
        exact norm_polarPartial_eq T x }
  have hclosed : IsClosed (Set.range W) :=
    W.antilipschitz.isClosed_range W.isometry.uniformContinuous
  have hdense : DenseRange W := denseRange_polarPartial_final T
  rw [DenseRange, dense_iff_closure_eq, hclosed.closure_eq] at hdense
  exact Set.range_eq_univ.mp hdense

/-- The polar partial isometry as a unitary between its initial and final
spaces. -/
noncomputable def polarPartialFinalEquiv (T : H →L[ℂ] H) :
    polarRange T ≃ₗᵢ[ℂ] polarFinalRange T :=
  LinearIsometryEquiv.ofSurjective
    { toLinearMap := ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)).toLinearMap
      norm_map' := fun x => by
        change ‖polarPartial T x‖ = ‖x‖
        exact norm_polarPartial_eq T x }
    (polarPartial_final_surjective T)

/-- The final projection identity for the polar isometry. -/
theorem polarIsometry_comp_adjoint_self (T : H →L[ℂ] H) :
    polarIsometry T ∘L (polarIsometry T)† =
      (polarFinalRange T).starProjection := by
  set U := polarIsometry T with hU
  -- `U` fixes the initial projection: `U ∘L P_K = U`.
  have hUP : U ∘L (polarRange T).starProjection = U := by
    ext w
    simp only [ContinuousLinearMap.comp_apply, hU, polarIsometry_apply_eq]
    congr 1
    have hsp : (polarRange T).starProjection w
        = ((polarRange T).orthogonalProjectionOnto w : H) := rfl
    rw [hsp]
    exact (polarRange T).orthogonalProjectionOnto_mem_subspace_eq_self _
  have hUadjU : U† ∘L U = (polarRange T).starProjection := polarIsometry_adjoint_comp_self T
  -- `(U U†) U = U`, so `U U†` is idempotent (and self-adjoint), a star projection.
  have hUUadjU : (U ∘L U†) ∘L U = U := by
    rw [ContinuousLinearMap.comp_assoc, hUadjU, hUP]
  have hsa : IsSelfAdjoint (U ∘L U†) := by
    rw [isSelfAdjoint_iff, ContinuousLinearMap.star_eq_adjoint,
      ContinuousLinearMap.adjoint_comp, ContinuousLinearMap.adjoint_adjoint]
  have hidem : IsIdempotentElem (U ∘L U†) := by
    change (U ∘L U†) ∘L (U ∘L U†) = U ∘L U†
    rw [← ContinuousLinearMap.comp_assoc, hUUadjU]
  have hSP : IsStarProjection (U ∘L U†) := ⟨hidem, hsa⟩
  -- The range of `U U†` is exactly the final polar space.
  have hrange : (U ∘L U†).range = polarFinalRange T := by
    apply le_antisymm
    · rintro _ ⟨x, rfl⟩
      show (U ∘L U†) x ∈ polarFinalRange T
      rw [ContinuousLinearMap.comp_apply, hU, polarIsometry_apply_eq]
      exact polarPartial_mem_finalRange T _
    · intro y hy
      obtain ⟨x, hx⟩ := polarPartial_final_surjective T ⟨y, hy⟩
      have hxy : (polarPartial T x : H) = y := congrArg Subtype.val hx
      have hUx : U (↑x : H) = y := by
        rw [hU, polarIsometry_apply_eq,
          (polarRange T).orthogonalProjectionOnto_mem_subspace_eq_self x, coe_polarPartialₗᵢ]
        exact hxy
      refine ⟨y, ?_⟩
      show (U ∘L U†) y = y
      conv_lhs => rw [← hUx]
      rw [← ContinuousLinearMap.comp_apply, hUUadjU, hUx]
  obtain ⟨_, heq⟩ := isStarProjection_iff_eq_starProjection_range.mp hSP
  rw [heq]
  congr 1

/-- The adjoint polar isometry is the polar isometry of the adjoint.

The proof is polar-decomposition uniqueness.  Writing `U = polarIsometry T` and
`W = polarIsometry T†`, we prove `U† = W` by showing they agree on the closed
range `L = closure (range T)` and vanish together on `Lᗮ = ker T†`.  The load
-bearing new identity is the abs-adjoint conjugation `|T†| = U |T| U†`, obtained
from square-root uniqueness in the C⋆-algebra `H →L[ℂ] H`: the conjugate is
nonnegative and squares to `T T†`.  From it, `T = |T†| U`, so on `range T` both
`U†` and `W` send `T x` to `|T| x`; the complement is handled by the two initial
/final projection identities. -/
theorem adjoint_polarIsometry (T : H →L[ℂ] H) :
    (polarIsometry T)† = polarIsometry (T†) := by
  -- Self-adjointness of the modulus and the initial projection, as adjoint
  -- identities usable by `rw`.
  have hSA_abs : (absOp T)† = absOp T := (absOp_isSelfAdjoint T).adjoint_eq
  -- Basic factorization identities for the polar decomposition of `T`.
  have hUS : polarIsometry T ∘L absOp T = T := polar_decomposition T
  have hUadjU : (polarIsometry T)† ∘L polarIsometry T = (polarRange T).starProjection :=
    polarIsometry_adjoint_comp_self T
  -- `|T| U† = T†` (adjoint of `U |T| = T`).
  have hSU : absOp T ∘L (polarIsometry T)† = T† := by
    have h := congrArg ContinuousLinearMap.adjoint hUS
    rwa [ContinuousLinearMap.adjoint_comp, hSA_abs] at h
  -- `T† U = |T|` (adjoint of `U† T = |T|`).
  have hTadjU : T† ∘L polarIsometry T = absOp T := by
    have h := congrArg ContinuousLinearMap.adjoint (polarIsometry_adjoint_comp T)
    rwa [ContinuousLinearMap.adjoint_comp, ContinuousLinearMap.adjoint_adjoint, hSA_abs] at h
  -- `P_K |T| = |T|` and `|T| P_K = |T|`, where `K = polarRange T`.
  have hPS : (polarRange T).starProjection ∘L absOp T = absOp T := by
    ext x
    simp only [ContinuousLinearMap.comp_apply]
    exact Submodule.starProjection_eq_self_iff.2 (absOp_mem_polarRange T x)
  have hSP : absOp T ∘L (polarRange T).starProjection = absOp T := by
    have h := congrArg ContinuousLinearMap.adjoint hPS
    simp only [ContinuousLinearMap.adjoint_comp, hSA_abs,
      (isSelfAdjoint_starProjection (polarRange T)).adjoint_eq] at h
    exact h
  -- **The abs-adjoint conjugation identity** `|T†| = U |T| U†`.
  have habs : absOp (T†) = polarIsometry T ∘L absOp T ∘L (polarIsometry T)† := by
    -- The conjugate is nonnegative.
    have hnonneg : 0 ≤ polarIsometry T ∘L absOp T ∘L (polarIsometry T)† := by
      have h := star_right_conjugate_nonneg (absOp_nonneg T) (polarIsometry T)
      simpa only [ContinuousLinearMap.star_eq_adjoint, ContinuousLinearMap.mul_def,
        ContinuousLinearMap.comp_assoc] using h
    -- The conjugate squares to `T ∘L T†`.
    have hAA : (polarIsometry T ∘L absOp T ∘L (polarIsometry T)†) ∘L
        (polarIsometry T ∘L absOp T ∘L (polarIsometry T)†) = T ∘L T† := by
      ext x
      simp only [ContinuousLinearMap.comp_apply]
      -- Collapse the inner `U† U` to `P_K`, which fixes `|T| (U† x)`.
      have e1 : ((polarIsometry T)†) (polarIsometry T (absOp T (((polarIsometry T)†) x))) = absOp T (((polarIsometry T)†) x) := by
        rw [← ContinuousLinearMap.comp_apply, hUadjU]
        exact Submodule.starProjection_eq_self_iff.2 (absOp_mem_polarRange T _)
      have e2 : polarIsometry T (absOp T (absOp T (((polarIsometry T)†) x))) = T (absOp T (((polarIsometry T)†) x)) := by
        rw [← ContinuousLinearMap.comp_apply, hUS]
      have e3 : absOp T (((polarIsometry T)†) x) = (T†) x := by
        rw [← ContinuousLinearMap.comp_apply, hSU]
      rw [e1, e2, e3]
    -- `star T† = T`, so the square target is `star T† * T†`.
    have hstar : star (T†) = T := by
      rw [ContinuousLinearMap.star_eq_adjoint, ContinuousLinearMap.adjoint_adjoint]
    have hgoal : (polarIsometry T ∘L absOp T ∘L (polarIsometry T)†)
        * (polarIsometry T ∘L absOp T ∘L (polarIsometry T)†) = star (T†) * (T†) := by
      rw [ContinuousLinearMap.mul_def, hAA, hstar, ← ContinuousLinearMap.mul_def]
    -- Conclude by square-root uniqueness.
    rw [show absOp (T†) = CFC.abs (T†) from rfl, CFC.abs]
    exact CFC.sqrt_unique hgoal hnonneg
  -- `T = |T†| U`, the left polar decomposition.
  have hT_left : absOp (T†) ∘L polarIsometry T = T := by
    ext x
    rw [ContinuousLinearMap.comp_apply, habs]
    simp only [ContinuousLinearMap.comp_apply]
    rw [show ((polarIsometry T)†) (polarIsometry T x) = (polarRange T).starProjection x from by
          rw [← ContinuousLinearMap.comp_apply, hUadjU]]
    rw [show absOp T ((polarRange T).starProjection x) = absOp T x from by
          rw [← ContinuousLinearMap.comp_apply, hSP]]
    rw [← ContinuousLinearMap.comp_apply, hUS]
  -- `W ∘L T = |T|`.
  have hWT : polarIsometry (T†) ∘L T = absOp T := by
    calc polarIsometry (T†) ∘L T
        = polarIsometry (T†) ∘L (absOp (T†) ∘L polarIsometry T) := by rw [hT_left]
      _ = (polarIsometry (T†) ∘L absOp (T†)) ∘L polarIsometry T := by
          rw [← ContinuousLinearMap.comp_assoc]
      _ = T† ∘L polarIsometry T := by rw [polar_decomposition]
      _ = absOp T := hTadjU
  -- The carrier of the final space is `closure (range T)`.
  have hFRcoe : (polarFinalRange T : Set H) = closure (Set.range (T : H → H)) := by
    rw [polarFinalRange, Submodule.topologicalClosure_coe, LinearMap.coe_range,
      ContinuousLinearMap.range_toLinearMap]
  -- Agreement on `L = polarFinalRange T`.
  have hL : ∀ y ∈ polarFinalRange T, ((polarIsometry T)†) y = polarIsometry (T†) y := by
    have hclosed : IsClosed {y : H | ((polarIsometry T)†) y = polarIsometry (T†) y} :=
      isClosed_eq ((polarIsometry T)†).continuous (polarIsometry (T†)).continuous
    have hsub : Set.range (T : H → H) ⊆
        {y : H | ((polarIsometry T)†) y = polarIsometry (T†) y} := by
      rintro _ ⟨x, rfl⟩
      show ((polarIsometry T)†) (T x) = polarIsometry (T†) (T x)
      rw [← ContinuousLinearMap.comp_apply, ← ContinuousLinearMap.comp_apply,
        polarIsometry_adjoint_comp T, hWT]
    intro y hy
    have hyc : (y : H) ∈ closure (Set.range (T : H → H)) := by rw [← hFRcoe]; exact hy
    exact (closure_minimal hsub hclosed) hyc
  -- Common vanishing on `Lᗮ`.
  have hLperp : ∀ y ∈ (polarFinalRange T)ᗮ,
      ((polarIsometry T)†) y = polarIsometry (T†) y := by
    intro y hy
    have hUy : ((polarIsometry T)†) y = 0 := by
      have hproj : polarIsometry T (((polarIsometry T)†) y) = 0 := by
        rw [← ContinuousLinearMap.comp_apply, polarIsometry_comp_adjoint_self T]
        exact (polarFinalRange T).starProjection_apply_eq_zero_iff.2 hy
      have hzero : ⟪((polarIsometry T)†) y, ((polarIsometry T)†) y⟫_ℂ = 0 := by
        rw [ContinuousLinearMap.adjoint_inner_left, hproj, inner_zero_right]
      exact inner_self_eq_zero.1 hzero
    have hWy : polarIsometry (T†) y = 0 := by
      have hTy : (T†) y = 0 := by
        have hmem : y ∈ (LinearMap.range T.toLinearMap)ᗮ := by
          have h := hy
          rwa [polarFinalRange, Submodule.orthogonal_closure] at h
        have hzero : ⟪(T†) y, (T†) y⟫_ℂ = 0 := by
          rw [ContinuousLinearMap.adjoint_inner_left]
          exact (Submodule.mem_orthogonal' _ _).1 hmem (T ((T†) y)) ⟨(T†) y, rfl⟩
        exact inner_self_eq_zero.1 hzero
      have hAbsy : absOp (T†) y = 0 := by
        have hn : ‖absOp (T†) y‖ = 0 := by rw [norm_absOp_apply, hTy, norm_zero]
        exact norm_eq_zero.1 hn
      have hyperp : (polarRange (T†)).starProjection y = 0 := by
        rw [Submodule.starProjection_apply_eq_zero_iff, polarRange,
          Submodule.orthogonal_closure, Submodule.mem_orthogonal]
        rintro u ⟨w, rfl⟩
        have hsym := (absOp_isSelfAdjoint (T†)).isSymmetric
        rw [hsym w y]
        show ⟪w, absOp (T†) y⟫_ℂ = 0
        rw [hAbsy, inner_zero_right]
      have hWadj : ((polarIsometry (T†))†) (polarIsometry (T†) y) = 0 := by
        rw [← ContinuousLinearMap.comp_apply, polarIsometry_adjoint_comp_self, hyperp]
      have hzero : ⟪polarIsometry (T†) y, polarIsometry (T†) y⟫_ℂ = 0 := by
        rw [← ContinuousLinearMap.adjoint_inner_left, hWadj, inner_zero_left]
      exact inner_self_eq_zero.1 hzero
    rw [hUy, hWy]
  -- Assemble via the orthogonal decomposition `x = P_L x + (x - P_L x)`.
  ext x
  have hPx : (polarFinalRange T).starProjection x ∈ polarFinalRange T :=
    Submodule.starProjection_apply_mem _ _
  have hrem : x - (polarFinalRange T).starProjection x ∈ (polarFinalRange T)ᗮ :=
    Submodule.sub_starProjection_mem_orthogonal x
  have hxadd : (polarFinalRange T).starProjection x
      + (x - (polarFinalRange T).starProjection x) = x := by abel
  conv_lhs => rw [← hxadd]
  conv_rhs => rw [← hxadd]
  rw [ContinuousLinearMap.map_add, ContinuousLinearMap.map_add, hL _ hPx, hLperp _ hrem]

end
end Channels
end QuantumMechanics
end Spectra
