/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/
import DavisKahan.Interop.Spectra.SpectralRestriction

/-!
# Self-adjoint operators on spectral ranges

For a self-adjoint operator `A` and a measurable spectral set `B`, this file
restricts the unitary group generated by `A` to the range of `E_A(B)`.  Stone's
theorem then supplies a self-adjoint generator on that closed spectral range.

The resulting closed operator is the canonical spectral part needed by the
bounded-perturbation sine-theta specialization.  Its subtype inclusion maps the
restricted generator domain into `A.domain` and intertwines the two operators.
This construction avoids a separate adjoint calculation for the raw graph
restriction.
-/

open scoped InnerProductSpace
open Filter Topology

namespace ForMathlib
namespace DavisKahan
namespace Experimental
namespace SpectraBridge

open Spectra.OneParameterUnitaryGroup
open Spectra.YosidaHille
open Spectra.QuantumMechanics.SpectralTheory

variable {H : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H]

/-- Spectral projections commute with the unitary group generated by the
self-adjoint operator. -/
theorem selfAdjointSpectralProjection_group_comm
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B) (t : ℝ) (x : H) :
    selfAdjointSpectralProjection A hA B hB ((genToGroup hA).U t x) =
      (genToGroup hA).U t (selfAdjointSpectralProjection A hA B hB x) := by
  change spectralProjection (genToGroup hA) B hB ((genToGroup hA).U t x) =
    (genToGroup hA).U t (spectralProjection (genToGroup hA) B hB x)
  simp only [spectralProjection]
  exact spectralCalculus_group_comm (genToGroup hA) _
    (measurable_const.indicator hB) (indicator_one_bdd B) t x

/-- The generated unitary flow preserves every measurable spectral range. -/
theorem selfAdjointSpectralSubspace_invariant_group
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B) (t : ℝ)
    (x : selfAdjointSpectralSubspace A hA B hB) :
    (genToGroup hA).U t (x : H) ∈ selfAdjointSpectralSubspace A hA B hB := by
  let P := Spectra.QuantumMechanics.SpectralTheory.PVM.spectralPVM hA
  change (genToGroup hA).U t (x : H) ∈ pvmRangeSubspace P B hB
  rw [mem_pvmRangeSubspace_iff P B hB]
  change selfAdjointSpectralProjection A hA B hB
      ((genToGroup hA).U t (x : H)) = (genToGroup hA).U t (x : H)
  rw [selfAdjointSpectralProjection_group_comm]
  have hx : selfAdjointSpectralProjection A hA B hB (x : H) = (x : H) := by
    change P.proj B hB (x : H) = (x : H)
    exact pvmProjection_eq_self_of_mem_rangeSubspace P B hB x.property
  rw [hx]

/-- The ambient unitary flow restricted to a measurable spectral range. -/
noncomputable def selfAdjointSpectralSubspaceEvolution
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B) (t : ℝ) :
    selfAdjointSpectralSubspace A hA B hB →L[ℂ]
      selfAdjointSpectralSubspace A hA B hB :=
  ((genToGroup hA).U t).restrict fun x hx =>
    selfAdjointSpectralSubspace_invariant_group A hA B hB t ⟨x, hx⟩

@[simp]
theorem selfAdjointSpectralSubspaceEvolution_apply
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B) (t : ℝ)
    (x : selfAdjointSpectralSubspace A hA B hB) :
    ((selfAdjointSpectralSubspaceEvolution A hA B hB t x :
        selfAdjointSpectralSubspace A hA B hB) : H) =
      (genToGroup hA).U t (x : H) :=
  rfl

/-- The strongly continuous unitary group induced on a measurable spectral
range. -/
noncomputable def selfAdjointSpectralSubspaceUnitaryGroup
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B) :
    Spectra.OneParameterUnitaryGroup
      (selfAdjointSpectralSubspace A hA B hB) where
  U := selfAdjointSpectralSubspaceEvolution A hA B hB
  unitary := by
    intro t x y
    change ⟪(genToGroup hA).U t (x : H),
        (genToGroup hA).U t (y : H)⟫_ℂ = ⟪(x : H), (y : H)⟫_ℂ
    exact (genToGroup hA).unitary t (x : H) (y : H)
  group_law := by
    intro s t
    apply ContinuousLinearMap.ext
    intro x
    apply Subtype.ext
    change (genToGroup hA).U (s + t) (x : H) =
      (genToGroup hA).U s ((genToGroup hA).U t (x : H))
    simpa only [ContinuousLinearMap.comp_apply] using
      DFunLike.congr_fun ((genToGroup hA).group_law s t) (x : H)
  identity := by
    apply ContinuousLinearMap.ext
    intro x
    apply Subtype.ext
    change (genToGroup hA).U 0 (x : H) = (x : H)
    simpa using DFunLike.congr_fun (genToGroup hA).identity (x : H)
  strong_continuous := by
    intro x
    change Continuous (fun t : ℝ =>
      (⟨(genToGroup hA).U t (x : H),
        selfAdjointSpectralSubspace_invariant_group A hA B hB t x⟩ :
          selfAdjointSpectralSubspace A hA B hB))
    exact ((genToGroup hA).strong_continuous (x : H)).subtype_mk
      (fun t => selfAdjointSpectralSubspace_invariant_group A hA B hB t x)

/-- Coercing the restricted difference quotient to the ambient space recovers
the ambient difference quotient. -/
@[simp]
theorem coe_genDiffQuot_selfAdjointSpectralSubspaceUnitaryGroup
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B)
    (x : selfAdjointSpectralSubspace A hA B hB) (t : ℝ) :
    ((genDiffQuot (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB) x t :
        selfAdjointSpectralSubspace A hA B hB) : H) =
      genDiffQuot (genToGroup hA) (x : H) t := by
  rfl

/-- The restricted generator converges in the ambient Hilbert space to the
included restricted-generator value. -/
theorem selfAdjointSpectralSubspace_generator_tendsto_ambient
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B)
    (x : (generator
      (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB)).domain) :
    Filter.Tendsto
      (genDiffQuot (genToGroup hA)
        ((x : selfAdjointSpectralSubspace A hA B hB) : H))
      (𝓝[≠] (0 : ℝ))
      (𝓝 (selfAdjointSpectralSubspaceInclusion A hA B hB
        (generator (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB) x))) := by
  have h :=
    ((selfAdjointSpectralSubspaceInclusion A hA B hB).continuous.tendsto
      (generator (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB) x)).comp
      (generator_tendsto
        (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB) x)
  exact h.congr fun t => by
    simpa only [Function.comp_apply,
      selfAdjointSpectralSubspaceInclusion_apply] using
      coe_genDiffQuot_selfAdjointSpectralSubspaceUnitaryGroup
        A hA B hB (x : selfAdjointSpectralSubspace A hA B hB) t

/-- The domain of the restricted generator embeds into the ambient generator
domain. -/
theorem selfAdjointSpectralSubspace_generator_mem_ambientDomain
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B)
    (x : (generator
      (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB)).domain) :
    ((x : selfAdjointSpectralSubspace A hA B hB) : H) ∈
      (generator (genToGroup hA)).domain := by
  exact mem_generatorDomain.mpr
    ⟨selfAdjointSpectralSubspaceInclusion A hA B hB
        (generator (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB) x),
      selfAdjointSpectralSubspace_generator_tendsto_ambient A hA B hB x⟩

/-- The inclusion intertwines the restricted and ambient Stone generators. -/
theorem selfAdjointSpectralSubspace_generator_intertwines
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B)
    (x : (generator
      (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB)).domain) :
    generator (genToGroup hA)
        ⟨((x : selfAdjointSpectralSubspace A hA B hB) : H),
          selfAdjointSpectralSubspace_generator_mem_ambientDomain A hA B hB x⟩ =
      selfAdjointSpectralSubspaceInclusion A hA B hB
        (generator (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB) x) := by
  exact tendsto_nhds_unique
    (generator_tendsto (genToGroup hA)
      ⟨((x : selfAdjointSpectralSubspace A hA B hB) : H),
        selfAdjointSpectralSubspace_generator_mem_ambientDomain A hA B hB x⟩)
    (selfAdjointSpectralSubspace_generator_tendsto_ambient A hA B hB x)

/-- The self-adjoint Spectra operator obtained by taking the Stone generator on
the spectral range. -/
noncomputable def selfAdjointSpectralRestrictionSpectra
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B) :
    Spectra.Operator.SelfAdjointOperator
      (selfAdjointSpectralSubspace A hA B hB) where
  toLinearPMap :=
    generator (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB)
  selfAdjoint := Spectra.Resolvent.generator_isSelfAdjoint
    (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB)

/-- The spectral-range Stone generator in the local closed-operator wrapper. -/
noncomputable def selfAdjointSpectralRestriction
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B) :
    DKClosedOperator (H := selfAdjointSpectralSubspace A hA B hB) :=
  closedOperatorOfSpectra
    (selfAdjointSpectralRestrictionSpectra A hA B hB)

/-- The spectral restriction is self-adjoint. -/
theorem selfAdjointSpectralRestriction_isSelfAdjoint
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B) :
    (selfAdjointSpectralRestriction A hA B hB).IsSelfAdjoint := by
  exact (selfAdjointSpectralRestrictionSpectra A hA B hB).selfAdjoint

/-- The spectral-range inclusion maps the restricted operator domain into the
ambient operator domain. -/
theorem selfAdjointSpectralRestriction_inclusion_mem_domain
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B)
    (x : (selfAdjointSpectralRestriction A hA B hB).domain) :
    selfAdjointSpectralSubspaceInclusion A hA B hB
        (x : selfAdjointSpectralSubspace A hA B hB) ∈ A.domain := by
  have hxgen :
      (((x : selfAdjointSpectralSubspace A hA B hB) : H)) ∈
        (generator (genToGroup hA)).domain :=
    selfAdjointSpectralSubspace_generator_mem_ambientDomain A hA B hB x
  have hdom : (generator (genToGroup hA)).domain = A.domain :=
    congrArg LinearPMap.domain (generator_genToGroup hA)
  exact (le_of_eq hdom) hxgen

/-- The spectral-range inclusion intertwines the restricted closed operator
with the ambient self-adjoint operator. -/
theorem selfAdjointSpectralRestriction_inclusion_intertwines
    (A : DKClosedOperator (H := H)) (hA : A.IsSelfAdjoint)
    (B : Set ℝ) (hB : MeasurableSet B)
    (x : (selfAdjointSpectralRestriction A hA B hB).domain) :
    A.toLinearMap
        ⟨selfAdjointSpectralSubspaceInclusion A hA B hB
            (x : selfAdjointSpectralSubspace A hA B hB),
          selfAdjointSpectralRestriction_inclusion_mem_domain A hA B hB x⟩ =
      selfAdjointSpectralSubspaceInclusion A hA B hB
        ((selfAdjointSpectralRestriction A hA B hB).toLinearMap x) := by
  have hgen := generator_genToGroup hA
  have happly := (LinearPMap.ext_iff.mp hgen).2
  have hambient :
      generator (genToGroup hA)
          ⟨((x : selfAdjointSpectralSubspace A hA B hB) : H),
            selfAdjointSpectralSubspace_generator_mem_ambientDomain A hA B hB x⟩ =
        selfAdjointSpectralSubspaceInclusion A hA B hB
          (generator (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB) x) :=
    selfAdjointSpectralSubspace_generator_intertwines A hA B hB x
  have htransport :
      generator (genToGroup hA)
          ⟨((x : selfAdjointSpectralSubspace A hA B hB) : H),
            selfAdjointSpectralSubspace_generator_mem_ambientDomain A hA B hB x⟩ =
        A.toLinearPMap
          ⟨((x : selfAdjointSpectralSubspace A hA B hB) : H),
            selfAdjointSpectralRestriction_inclusion_mem_domain A hA B hB x⟩ :=
    happly
      (x := ((x : selfAdjointSpectralSubspace A hA B hB) : H))
      (hf := selfAdjointSpectralSubspace_generator_mem_ambientDomain A hA B hB x)
      (hg := selfAdjointSpectralRestriction_inclusion_mem_domain A hA B hB x)
  calc
    A.toLinearMap
        ⟨selfAdjointSpectralSubspaceInclusion A hA B hB
            (x : selfAdjointSpectralSubspace A hA B hB),
          selfAdjointSpectralRestriction_inclusion_mem_domain A hA B hB x⟩ =
        generator (genToGroup hA)
          ⟨((x : selfAdjointSpectralSubspace A hA B hB) : H),
            selfAdjointSpectralSubspace_generator_mem_ambientDomain A hA B hB x⟩ :=
      htransport.symm
    _ = selfAdjointSpectralSubspaceInclusion A hA B hB
          (generator (selfAdjointSpectralSubspaceUnitaryGroup A hA B hB) x) :=
      hambient
    _ = selfAdjointSpectralSubspaceInclusion A hA B hB
          ((selfAdjointSpectralRestriction A hA B hB).toLinearMap x) := rfl

end SpectraBridge
end Experimental
end DavisKahan
end ForMathlib
