#!/usr/bin/env python3
"""Validate dated evidence and build reproducibility artifacts for the paper."""
from __future__ import annotations

import csv
import hashlib
import json
import subprocess
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAPER = HERE.parent


def git_root() -> Path:
    try:
        out = subprocess.check_output(
            ['git', 'rev-parse', '--show-toplevel'],
            cwd=PAPER,
            text=True,
            stderr=subprocess.DEVNULL,
        )
        return Path(out.strip())
    except Exception:
        return PAPER.parents[1]


REPO = git_root()


def git(*args: str) -> str:
    cmd = ['git', '-c', f'safe.directory={REPO}', *args]
    return subprocess.check_output(
        cmd, cwd=REPO, text=True, stderr=subprocess.STDOUT
    ).strip()


def load_csv(path: Path):
    with path.open(newline='', encoding='utf8') as f:
        return list(csv.DictReader(f))


def tex_escape(text: str) -> str:
    repl = {
        '\\': r'\textbackslash{}',
        '&': r'\&',
        '%': r'\%',
        '$': r'\$',
        '#': r'\#',
        '_': r'\_',
        '{': r'\{',
        '}': r'\}',
        '~': r'\textasciitilde{}',
        '^': r'\textasciicircum{}',
    }
    return ''.join(repl.get(c, c) for c in text)


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with path.open('rb') as f:
        for block in iter(lambda: f.read(1 << 20), b''):
            h.update(block)
    return h.hexdigest()


def validate_timeline(rows):
    errors = []
    for i, r in enumerate(rows, 2):
        commit = r['commit']
        try:
            full = git('rev-parse', commit)
            commit_date = git('show', '-s', '--format=%aI', full)
        except Exception as ex:
            errors.append(f'row {i}: cannot resolve commit {commit}: {ex}')
            continue
        if commit_date[:10] != r['datetime'][:10]:
            errors.append(
                f'row {i}: date mismatch for {commit}: '
                f'csv={r["datetime"]} git={commit_date}'
            )
        evidence = REPO / r['evidence_path']
        if not evidence.exists():
            errors.append(f'row {i}: evidence path missing: {r["evidence_path"]}')
    if errors:
        raise SystemExit('\n'.join(errors))


def build_timeline_table(rows):
    out = PAPER / 'generated' / 'review_timeline_table.tex'
    labels = {
        'dk_work_begins': 'Dedicated Davis--Kahan formalization begins',
        'source_comparison_finds_mismatch': 'Source comparison finds incomplete coverage',
        'broad_review': 'Broader source comparison finds remaining gaps',
        'apparent_completion': 'Project checks reach 29/29',
        'new_gap_found': 'Follow-up review finds another scope gap',
        'gap_repaired': 'Source-shaped endpoint added',
        'paper_snapshot': 'Paper evidence snapshot',
    }
    lines = []
    for r in rows:
        date = r['datetime'][:10]
        short = r['commit'][:8]
        label = labels.get(r['event'], r['event'].replace('_', ' '))
        lines.append(f'{date} & \\texttt{{{short}}} & {tex_escape(label)} \\\\')
    lines.append('\\bottomrule')
    out.write_text('\n'.join(lines) + '\n', encoding='utf8')


def build_activity_tikz():
    rows = load_csv(PAPER / 'data' / 'lean_publication_activity.csv')
    values = [int(r['papers_indexed']) for r in rows]
    if len(values) != 19:
        raise SystemExit('expected 19 complete months Jan 2025--Jul 2026')
    coords = ' '.join(f'({i},{v})' for i, v in enumerate(values))
    bars = '\n'.join(
        f'  \\fill[black!18] ({i - 0.33},0) rectangle ({i + 0.33},{v});'
        for i, v in enumerate(values)
    )
    labels = [
        (0, 'Jan 25'),
        (3, 'Apr 25'),
        (6, 'Jul 25'),
        (9, 'Oct 25'),
        (12, 'Jan 26'),
        (15, 'Apr 26'),
        (18, 'Jul 26'),
    ]
    xlabels = '\n'.join(
        f'  \\node[anchor=north, font=\\scriptsize] at ({x},-5) {{{label}}};'
        for x, label in labels
    )
    yticks = '\n'.join(
        f'  \\draw (-0.5,{y}) -- (-0.25,{y}) '
        f'node[left, font=\\scriptsize] {{{y}}};'
        for y in [0, 25, 50, 75, 100]
    )
    text = rf'''% Generated by scripts/build_evidence.py
\begin{{tikzpicture}}[x=0.52cm,y=0.045cm]
{bars}
  \draw[thick] (-0.5,0) -- (18.55,0);
  \draw[thick] (-0.5,0) -- (-0.5,108);
{yticks}
{xlabels}
  \draw[blue!70!black, very thick] plot coordinates {{{coords}}};
  \draw[red!70!black, dashed, thick] (18.39,0) -- (18.39,108);
  \node[anchor=east, align=right, font=\scriptsize, text=red!60!black]
    at (18.25,92) {{dedicated DK work\\begins 13 Jul 2026}};
  \node[rotate=90, anchor=south, font=\scriptsize] at (-2.05,54)
    {{indexed papers / month}};
\end{{tikzpicture}}
'''
    (PAPER / 'generated' / 'lean_activity_timeline_tikz.tex').write_text(
        text, encoding='utf8'
    )


def build_resource_table():
    rows = load_csv(PAPER / 'data' / 'resource_snapshot.csv')
    pretty = {
        'retained_model_turns': 'Retained model turns',
        'output_tokens': 'Output tokens',
        'billable_input_accounting_measure': 'Billable-input accounting measure',
        'exact_commit_attribution': 'Exact commit attribution',
        'api_equivalent_list_price': 'API-equivalent list price',
        'operational_serving_energy': 'Operational serving energy',
    }
    basis = {
        'observed_lower_bound': 'Observed lower bound.',
        'coverage': 'Coverage.',
        'modeled_from_observed': 'Modeled from observed telemetry.',
    }
    lines = []
    for r in rows:
        value = r['value']
        if r['unit'] == 'USD':
            value = r'\$' + f'{int(float(value)):,}'
        elif r['unit'] == 'kWh':
            value = f'{float(value):,.1f} kWh'
        elif r['unit'] == 'tokens' and '/' not in value:
            value = f'{int(value):,}'
        elif r['unit'] == 'turns':
            value = f'{int(value):,}'
        note = f'{basis[r["category"]]} {r["interpretation"]}'
        lines.append(
            f'{tex_escape(pretty.get(r["quantity"], r["quantity"]))} & '
            f'{value} & {tex_escape(note)} \\\\'
        )
    lines.append('\\bottomrule')
    (PAPER / 'generated' / 'resource_snapshot_table.tex').write_text(
        '\n'.join(lines) + '\n', encoding='utf8'
    )



def build_historical_false_finish():
    """Extract the historical Lean signature shown as Formalization 1."""
    commit = '7001ed05'
    source_path = 'DavisKahan/Sources/DavisKahan1970/SinTwoThetaWholeSpace.lean'
    full_commit = git('rev-parse', commit)
    raw = subprocess.check_output(
        ['git', '-c', f'safe.directory={REPO}', 'show', f'{full_commit}:{source_path}'],
        cwd=REPO,
    )
    text = raw.decode('utf8')
    lines = text.splitlines()
    variable_start = next(
        i for i, line in enumerate(lines)
        if line.startswith('variable {E : Type v}')
    )
    theorem_start = next(
        i for i, line in enumerate(lines)
        if line.startswith('theorem sinTwoTheta_directedResidual_paperUINorm')
    )
    theorem_end = next(
        i for i in range(theorem_start, len(lines))
        if lines[i].rstrip().endswith(':= by')
    )
    signature_lines = (
        lines[variable_start:variable_start + 2]
        + ['']
        + lines[theorem_start:theorem_end + 1]
    )
    signature = '\n'.join(signature_lines) + '\n'
    payload = {
        'schema_version': 1,
        'commit': full_commit,
        'source_path': source_path,
        'source_file_sha256': hashlib.sha256(raw).hexdigest(),
        'variable_line_range_1based': [variable_start + 1, variable_start + 2],
        'theorem_signature_line_range_1based': [theorem_start + 1, theorem_end + 1],
        'signature_sha256': hashlib.sha256(signature.encode('utf8')).hexdigest(),
        'signature': signature,
        'note': (
            'Formalization 1 reformats the two-line variable declaration for '
            'page width and omits the proof body; the theorem signature is otherwise '
            'transcribed from this extraction.'
        ),
    }
    out = PAPER / 'generated' / 'historical_false_finish.json'
    out.write_text(json.dumps(payload, indent=2, sort_keys=True) + '\n', encoding='utf8')

def build_manifest():
    relpaths = [
        'papers/formalization_process_4page/paper.tex',
        'papers/formalization_process_4page/appendix.tex',
        'papers/formalization_process_4page/references.bib',
        'papers/formalization_process_4page/brainstorm.md',
        'papers/formalization_process_4page/data/practitioner_accounts.csv',
        'papers/formalization_process_4page/data/practitioner_accounts.schema.json',
        'papers/formalization_process_4page/data/lean_publication_activity.csv',
        'papers/formalization_process_4page/data/review_timeline.csv',
        'papers/formalization_process_4page/data/resource_snapshot.csv',
        'papers/formalization_process_4page/figures/formalization_workflow.png',
        'papers/formalization_process_4page/figures/semantic-alignment-sine-theta-row.png',
        'papers/formalization_process_4page/generated/historical_false_finish.json',
        'DavisKahan/Sources/DavisKahan1970/SineTheta/Presentation.lean',
        'dev/davis-kahan-1970-formalization-result-inventory.json',
        'dev/davis-kahan-1970-full-source-census.json',
        'prose/distilled_literature/DavisKahan1970_part_III.tex',
        'submodules/aiq-lean-formalization-tools/README.md',
    ]
    artifacts = []
    for rel in relpaths:
        path = REPO / rel
        if not path.exists():
            artifacts.append({'path': rel, 'status': 'missing'})
        else:
            artifacts.append(
                {
                    'path': rel,
                    'status': 'present',
                    'bytes': path.stat().st_size,
                    'sha256': sha256(path),
                }
            )

    present_lines = [
        f'{a["path"]}\t{a["sha256"]}\n'
        for a in artifacts
        if a['status'] == 'present'
    ]
    aggregate = hashlib.sha256(
        ''.join(sorted(present_lines)).encode()
    ).hexdigest()
    try:
        head = git('rev-parse', 'HEAD')
    except Exception:
        head = 'unavailable'
    try:
        sub = git(
            'submodule', 'status', '--', 'submodules/aiq-lean-formalization-tools'
        ).split()[0].lstrip('-+U')
    except Exception:
        sub = 'unavailable'
    manifest = {
        'schema_version': 1,
        'repository_head': head,
        'formalization_tools_submodule': sub,
        'aggregate_sha256': aggregate,
        'aggregate_definition': (
            'sha256 of sorted UTF-8 lines path\\tsha256\\n for all present artifacts'
        ),
        'artifacts': artifacts,
    }
    out_json = PAPER / 'generated' / 'materials_manifest.json'
    out_json.write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + '\n', encoding='utf8'
    )

    show = {
        'papers/formalization_process_4page/paper.tex': 'workshop paper source',
        'papers/formalization_process_4page/data/practitioner_accounts.csv': 'public-account snapshot',
        'papers/formalization_process_4page/data/practitioner_accounts.schema.json': 'account-field schema',
        'papers/formalization_process_4page/data/review_timeline.csv': 'selected Git chronology',
        'papers/formalization_process_4page/generated/historical_false_finish.json': 'historical sin2Theta signature',
        'DavisKahan/Sources/DavisKahan1970/SineTheta/Presentation.lean': 'current sine-theta Lean source',
        'dev/davis-kahan-1970-formalization-result-inventory.json': '29-result tracking data',
        'dev/davis-kahan-1970-full-source-census.json': 'source-comparison data',
        'prose/distilled_literature/DavisKahan1970_part_III.tex': 'Davis--Kahan source reconstruction',
    }
    rows = []
    for a in artifacts:
        label = show.get(a['path'])
        if label is None:
            continue
        if a['status'] == 'present':
            rows.append(
                f'{tex_escape(label)} & '
                f'\\texttt{{{a["sha256"][:16]}}} & {a["bytes"]:,} \\\\'
            )
        else:
            rows.append(f'{tex_escape(label)} & missing & -- \\\\')
    macros = [
        '% Generated by scripts/build_evidence.py',
        f'\\newcommand{{\\EvidenceSnapshotCommit}}{{{head}}}',
        f'\\newcommand{{\\EvidenceSnapshotShort}}{{{head[:8] if head != "unavailable" else head}}}',
        f'\\newcommand{{\\FormalizationToolsCommit}}{{{sub}}}',
        f'\\newcommand{{\\MaterialsAggregateSHA}}{{{aggregate}}}',
        '\\newcommand{\\MaterialHashRows}{%',
        *[r + '%' for r in rows],
        '}',
    ]
    (PAPER / 'generated' / 'evidence_macros.tex').write_text(
        '\n'.join(macros) + '\n', encoding='utf8'
    )


def main():
    (PAPER / 'generated').mkdir(exist_ok=True)
    timeline = load_csv(PAPER / 'data' / 'review_timeline.csv')
    validate_timeline(timeline)
    build_timeline_table(timeline)
    build_activity_tikz()
    build_resource_table()
    build_historical_false_finish()
    build_manifest()
    print(f'validated {len(timeline)} Git timeline events against {REPO}')
    print('wrote generated evidence, timeline, resource, and hash artifacts')


if __name__ == '__main__':
    main()
