import DkpsQuench2026.QueryEfficiency.Spectral
import DkpsQuench2026.QueryEfficiency.Assumptions
import DkpsQuench2026.QueryEfficiency.Finite
import DkpsQuench2026.QueryEfficiency.Infinite
import DkpsQuench2026.QueryEfficiency.AllQueries
