/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, GPT 5.6 High
-/
import DavisKahan.Experimental.InfiniteDimensional.Core.Compatibility

/-!
# Spectral projections and bounded Borel calculus

The central object is one spectral resolution of a bounded self-adjoint
operator.  Indicator functions and bounded Borel integration are fields of the
same object, so projection algebra and functional-calculus identities cannot
drift apart.  For a non-self-adjoint operator the public totalized definitions
return zero; all mathematical theorems retain an explicit self-adjointness
hypothesis.

The construction follows the bounded spectral theorem.  In the complex case,
take the commutative C-star algebra generated by the operator, use the Gelfand
representation, apply Riesz--Markov to the vector states, polarize to obtain
complex measures, and reconstruct a projection-valued measure.  In the real
case, complexify, construct the conjugation-invariant resolution, and descend
to the fixed real subspace.
-/

namespace ForMathlib
namespace DavisKahanExt

open scoped InnerProductSpace
open Filter

variable {𝕜 : Type*} [RCLike 𝕜]
variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace 𝕜 E]
  [CompleteSpace E]

/-- Strong countable additivity in the strong operator topology. -/
def StronglyCountablyAdditive
    (P : Set ℝ → E →L[𝕜] E) : Prop :=
  ∀ (s : ℕ → Set ℝ), (∀ i, MeasurableSet (s i)) →
    (Pairwise fun i j => Disjoint (s i) (s j)) →
    ∀ x, Tendsto
      (fun n => ∑ i ∈ Finset.range n, P (s i) x)
      atTop (nhds (P (⋃ i, s i) x))

/-- A bounded self-adjoint spectral resolution, including its bounded Borel
integral. -/
structure BoundedSpectralResolution (A : E →L[𝕜] E) where
  projection : Set ℝ → E →L[𝕜] E
  integral : (ℝ → ℝ) → E →L[𝕜] E
  projection_empty : projection ∅ = 0
  projection_univ : projection Set.univ = ContinuousLinearMap.id 𝕜 E
  projection_inter : ∀ s t, MeasurableSet s → MeasurableSet t →
    projection s ∘L projection t = projection (s ∩ t)
  projection_selfAdjoint : ∀ s, MeasurableSet s → IsSelfAdjoint (projection s)
  projection_compl : ∀ s, MeasurableSet s →
    projection sᶜ = ContinuousLinearMap.id 𝕜 E - projection s
  operator_comm : ∀ s, MeasurableSet s →
    A ∘L projection s = projection s ∘L A
  stronglyCountablyAdditive : StronglyCountablyAdditive projection
  support : ∀ s, MeasurableSet s → Disjoint s (realSpectrum A) → projection s = 0
  integral_indicator : ∀ s, MeasurableSet s →
    integral (s.indicator fun _ => 1) = projection s
  integral_mul : ∀ f g, Measurable f → Measurable g →
    BoundedOnSpectrum A f → BoundedOnSpectrum A g →
    integral (fun x => f x * g x) = integral f ∘L integral g
  norm_integral_le : ∀ f, Measurable f → ∀ C, 0 ≤ C →
    (∀ x ∈ realSpectrum A, |f x| ≤ C) → ‖integral f‖ ≤ C

/-- Existence of the bounded spectral resolution. -/
theorem exists_boundedSpectralResolution
    (A : E →L[𝕜] E) (hA : IsSelfAdjointOperator A) :
    Nonempty (BoundedSpectralResolution A) := by
  classical
  let C := selfAdjointGeneratedCStarAlgebra A hA
  let X := CharacterSpace C
  let Γ : C ≃⋆ₐ[𝕜] C(X, 𝕜) := gelfandTransformEquiv C
  let a : C := ⟨A, generator_mem_selfAdjointGenerated A hA⟩
  have ha_real : ∀ χ : X, RCLike.im (Γ a χ) = 0 := by
    intro χ
    exact character_apply_selfAdjoint_real χ a.property
  let λ : X → ℝ := fun χ => RCLike.re (Γ a χ)
  have hλ : Continuous λ := by fun_prop
  have hspec : Set.range λ = realSpectrum A :=
    gelfand_range_generator_eq_realSpectrum A hA Γ
  let μ : E → E → Measure X := fun x y =>
    polarizationMeasure (fun z => rieszMeasure
      (positiveVectorFunctionalOnCStarAlgebra C z)) x y
  have hμ_add : ∀ x y, CountablyAdditive (μ x y) := by
    intro x y
    exact polarizationMeasure_countablyAdditive _
  let P : Set ℝ → E →L[𝕜] E := fun s =>
    operatorOfBoundedSesquilinearForm
      (fun x y => ∫ χ in λ ⁻¹' s, 1 ∂μ x y)
      (spectralIndicatorForm_bounded μ λ s)
  have hP_empty : P ∅ = 0 := by
    ext x y
    simp [P]
  have hP_univ : P Set.univ = ContinuousLinearMap.id 𝕜 E := by
    ext x y
    simp [P, μ, vectorFunctional_univ]
  have hP_inter : ∀ s t, MeasurableSet s → MeasurableSet t →
      P s ∘L P t = P (s ∩ t) := by
    intro s t hs ht
    ext x y
    rw [spectralIndicatorForm_comp]
    simp [P, Set.preimage_inter, hs, ht]
  have hPstar : ∀ s, MeasurableSet s → IsSelfAdjoint (P s) := by
    intro s hs
    apply ContinuousLinearMap.isSelfAdjoint_iff_isSymmetric.mpr
    intro x y
    simp [P, integral_conj, hs]
  have hPcompl : ∀ s, MeasurableSet s →
      P sᶜ = ContinuousLinearMap.id 𝕜 E - P s := by
    intro s hs
    ext x y
    simp [P, ← integral_add_compl hs, hP_univ]
  have hcomm : ∀ s, MeasurableSet s → A ∘L P s = P s ∘L A := by
    intro s hs
    ext x y
    simp [P, a, λ, spectralIndicatorForm_generator_comm, hs]
  have hadd : StronglyCountablyAdditive P := by
    intro s hs hd x
    apply tendsto_of_norm_tendsto_zero
    have horth : Pairwise fun i j => Orthogonal (P (s i) x) (P (s j) x) := by
      intro i j hij
      rw [orthogonal_iff_inner_eq_zero, ← ContinuousLinearMap.adjoint_inner_left,
        (hPstar _ (hs i)).adjoint_eq, ← ContinuousLinearMap.comp_apply,
        hP_inter _ _ (hs i) (hs j)]
      simp [Set.inter_eq_empty.mpr (hd hij).eq_bot]
    exact orthogonalSeries_tendsto_projection_union hP_inter hPstar hμ_add hs hd horth x
  have hsupport : ∀ s, MeasurableSet s → Disjoint s (realSpectrum A) → P s = 0 := by
    intro s hs hdisj
    ext x y
    have hpre : λ ⁻¹' s = ∅ := by
      ext χ
      simpa [hspec] using hdisj.not_mem_of_mem_right ⟨χ, rfl⟩
    simp [P, hpre]
  let I : (ℝ → ℝ) → E →L[𝕜] E := fun f =>
    operatorOfBoundedSesquilinearForm
      (fun x y => ∫ χ, (f (λ χ) : 𝕜) ∂μ x y)
      (spectralIntegralForm_bounded μ λ f)
  have hIind : ∀ s, MeasurableSet s → I (s.indicator fun _ => 1) = P s := by
    intro s hs
    ext x y
    simp [I, P, Measure.restrict_apply hs, Set.indicator]
  have hImul : ∀ f g, Measurable f → Measurable g →
      BoundedOnSpectrum A f → BoundedOnSpectrum A g →
      I (fun x => f x * g x) = I f ∘L I g := by
    intro f g hf hg hfb hgb
    refine bounded_measurable_function_monotoneClass
      (fun f => I (fun x => f x * g x) = I f ∘L I g) ?_ ?_ ?_ hf hfb
    · intro s hs
      rw [hIind s hs]
      exact spectralIntegral_indicator_mul P I hP_inter hIind hs hg hgb
    · exact spectralIntegral_linear_limit I μ
    · exact spectralIntegral_bounded_convergence I μ
  have hInorm : ∀ f, Measurable f → ∀ C, 0 ≤ C →
      (∀ x ∈ realSpectrum A, |f x| ≤ C) → ‖I f‖ ≤ C := by
    intro f hf C hC hbound
    refine ContinuousLinearMap.opNorm_le_bound _ hC ?_
    intro x
    have hsq := spectralIntegral_norm_sq I μ λ f x
    have hbound' : ∀ χ, |f (λ χ)| ≤ C := by
      intro χ
      apply hbound
      rw [← hspec]
      exact ⟨χ, rfl⟩
    calc
      ‖I f x‖ ^ 2 = ∫ χ, |f (λ χ)|^2 ∂μ x x := hsq
      _ ≤ ∫ χ, C^2 ∂μ x x := integral_mono_measure (fun χ => by nlinarith [hbound' χ])
      _ = (C * ‖x‖)^2 := by simp [μ, sq, hC]
    exact nonneg_le_nonneg_of_sq_le_sq (norm_nonneg _) (mul_nonneg hC (norm_nonneg _)) this
  exact ⟨{
    projection := P
    integral := I
    projection_empty := hP_empty
    projection_univ := hP_univ
    projection_inter := hP_inter
    projection_selfAdjoint := hPstar
    projection_compl := hPcompl
    operator_comm := hcomm
    stronglyCountablyAdditive := hadd
    support := hsupport
    integral_indicator := hIind
    integral_mul := hImul
    norm_integral_le := hInorm }

/-- Chosen spectral resolution of a self-adjoint operator. -/
noncomputable def spectralResolution (A : E →L[𝕜] E)
    (hA : IsSelfAdjointOperator A) : BoundedSpectralResolution A :=
  Classical.choice (exists_boundedSpectralResolution A hA)

/-- Spectral projection, totalized by zero outside the measurable self-adjoint
branch. -/
noncomputable def spectralProjection (A : E →L[𝕜] E) (s : Set ℝ) : E →L[𝕜] E := by
  classical
  if hA : IsSelfAdjointOperator A then
    if hs : MeasurableSet s then
      exact (spectralResolution A hA).projection s
    else
      exact 0
  else
    exact 0

/-- Spectral subspace associated with a Borel set. -/
noncomputable def spectralSubspace (A : E →L[𝕜] E) (s : Set ℝ) : Submodule 𝕜 E :=
  LinearMap.range (spectralProjection A s).toLinearMap

/-- Spectral subspaces admit orthogonal projection. -/
noncomputable instance spectralSubspace_hasOrthogonalProjection
    (A : E →L[𝕜] E) (s : Set ℝ) :
    (spectralSubspace A s).HasOrthogonalProjection := by
  classical
  by_cases hA : IsSelfAdjointOperator A
  · by_cases hs : MeasurableSet s
    · have hp : IsOrthogonalProjection (spectralProjection A s) := by
        constructor
        · unfold spectralProjection
          rw [dif_pos hA, dif_pos hs, ← ContinuousLinearMap.mul_def,
            (spectralResolution A hA).projection_inter s s hs hs]
          simp
        · unfold spectralProjection
          rw [dif_pos hA, dif_pos hs]
          exact (spectralResolution A hA).projection_selfAdjoint s hs
      exact hp.range_hasOrthogonalProjection
    · simp [spectralSubspace, spectralProjection, hA, hs]
  · simp [spectralSubspace, spectralProjection, hA]

/-- Bounded Borel functional calculus, totalized by zero when its hypotheses
fail. -/
noncomputable def boundedBorelFunctionalCalculus
    (A : E →L[𝕜] E) (f : ℝ → ℝ) : E →L[𝕜] E := by
  classical
  if hA : IsSelfAdjointOperator A then
    if hf : Measurable f then
      if hfb : BoundedOnSpectrum A f then
        exact (spectralResolution A hA).integral f
      else
        exact 0
    else
      exact 0
  else
    exact 0

@[simp] theorem spectralProjection_empty (A : E →L[𝕜] E)
    (hA : IsSelfAdjointOperator A) : spectralProjection A ∅ = 0 := by
  unfold spectralProjection
  rw [dif_pos hA, dif_pos MeasurableSet.empty]
  exact (spectralResolution A hA).projection_empty

@[simp] theorem spectralProjection_univ (A : E →L[𝕜] E)
    (hA : IsSelfAdjointOperator A) :
    spectralProjection A Set.univ = ContinuousLinearMap.id 𝕜 E := by
  unfold spectralProjection
  rw [dif_pos hA, dif_pos MeasurableSet.univ]
  exact (spectralResolution A hA).projection_univ

/-- Multiplication of indicator functions becomes intersection. -/
theorem spectralProjection_comp (A : E →L[𝕜] E)
    (hA : IsSelfAdjointOperator A) (s t : Set ℝ)
    (hs : MeasurableSet s) (ht : MeasurableSet t) :
    spectralProjection A s ∘L spectralProjection A t =
      spectralProjection A (s ∩ t) := by
  unfold spectralProjection
  rw [dif_pos hA, dif_pos hs, dif_pos hA, dif_pos ht,
    dif_pos hA, dif_pos (hs.inter ht)]
  exact (spectralResolution A hA).projection_inter s t hs ht

/-- Every measurable spectral projection is orthogonal. -/
theorem spectralProjection_isOrthogonalProjection
    (A : E →L[𝕜] E) (hA : IsSelfAdjointOperator A)
    (s : Set ℝ) (hs : MeasurableSet s) :
    IsOrthogonalProjection (spectralProjection A s) := by
  constructor
  · rw [← ContinuousLinearMap.mul_def, spectralProjection_comp A hA s s hs hs]
    simp
  · unfold spectralProjection
    rw [dif_pos hA, dif_pos hs]
    exact (spectralResolution A hA).projection_selfAdjoint s hs

/-- Spectral projections commute with the generating operator. -/
theorem spectralProjection_comm (A : E →L[𝕜] E)
    (hA : IsSelfAdjointOperator A) (s : Set ℝ) (hs : MeasurableSet s) :
    A ∘L spectralProjection A s = spectralProjection A s ∘L A := by
  unfold spectralProjection
  rw [dif_pos hA, dif_pos hs]
  exact (spectralResolution A hA).operator_comm s hs

/-- Spectral subspaces reduce the operator. -/
theorem reduces_spectralSubspace (A : E →L[𝕜] E)
    (hA : IsSelfAdjointOperator A) (s : Set ℝ) (hs : MeasurableSet s) :
    Reduces A (spectralSubspace A s) := by
  have hcomm := spectralProjection_comm A hA s hs
  refine reduces_orthogonalComplement hA ?_
  rintro _ ⟨x, rfl⟩
  refine ⟨A x, ?_⟩
  exact congrArg (fun T : E →L[𝕜] E => T x) hcomm.symm

omit [CompleteSpace E] in
/-- The range of the projection is definitionally the spectral subspace. -/
theorem range_spectralProjection (A : E →L[𝕜] E) (s : Set ℝ) :
    LinearMap.range (spectralProjection A s).toLinearMap = spectralSubspace A s :=
  rfl

/-- Complementary sets give complementary projections. -/
theorem spectralProjection_compl (A : E →L[𝕜] E)
    (hA : IsSelfAdjointOperator A) (s : Set ℝ) (hs : MeasurableSet s) :
    spectralProjection A sᶜ =
      ContinuousLinearMap.id 𝕜 E - spectralProjection A s := by
  unfold spectralProjection
  rw [dif_pos hA, dif_pos hs.compl, dif_pos hA, dif_pos hs]
  exact (spectralResolution A hA).projection_compl s hs

/-- Strong countable additivity of the spectral resolution. -/
theorem spectralProjection_stronglyCountablyAdditive (A : E →L[𝕜] E)
    (hA : IsSelfAdjointOperator A) :
    StronglyCountablyAdditive (spectralProjection A) := by
  intro s hs hdisj x
  have hfield := (spectralResolution A hA).stronglyCountablyAdditive s hs hdisj x
  simpa [spectralProjection, hA, hs, MeasurableSet.iUnion hs] using hfield

/-- The spectral resolution is supported on the real spectrum. -/
theorem spectralProjection_eq_zero_of_disjoint_spectrum
    (A : E →L[𝕜] E) (hA : IsSelfAdjointOperator A)
    (s : Set ℝ) (hs : MeasurableSet s)
    (h : Disjoint s (realSpectrum A)) : spectralProjection A s = 0 := by
  unfold spectralProjection
  rw [dif_pos hA, dif_pos hs]
  exact (spectralResolution A hA).support s hs h

/-- Indicator functions recover spectral projections. -/
theorem boundedBorelFunctionalCalculus_indicator
    (A : E →L[𝕜] E) (hA : IsSelfAdjointOperator A)
    (s : Set ℝ) (hs : MeasurableSet s) :
    boundedBorelFunctionalCalculus A (s.indicator fun _ => 1) =
      spectralProjection A s := by
  let f : ℝ → ℝ := s.indicator fun _ => 1
  have hf : Measurable f := hs.indicator measurable_const
  have hfb : BoundedOnSpectrum A f := by
    refine ⟨1, fun x hx => ?_⟩
    simp [f]
  unfold boundedBorelFunctionalCalculus spectralProjection
  rw [dif_pos hA, dif_pos hf, dif_pos hfb, dif_pos hA, dif_pos hs]
  exact (spectralResolution A hA).integral_indicator s hs

/-- Multiplicativity of bounded Borel functional calculus. -/
theorem boundedBorelFunctionalCalculus_mul
    (A : E →L[𝕜] E) (hA : IsSelfAdjointOperator A)
    (f g : ℝ → ℝ) (hf : Measurable f) (hg : Measurable g)
    (hfb : BoundedOnSpectrum A f) (hgb : BoundedOnSpectrum A g) :
    boundedBorelFunctionalCalculus A (fun x => f x * g x) =
      boundedBorelFunctionalCalculus A f ∘L
        boundedBorelFunctionalCalculus A g := by
  have hfgb : BoundedOnSpectrum A (fun x => f x * g x) := hfb.mul hgb
  unfold boundedBorelFunctionalCalculus
  rw [dif_pos hA, dif_pos (hf.mul hg), dif_pos hfgb,
    dif_pos hA, dif_pos hf, dif_pos hfb,
    dif_pos hA, dif_pos hg, dif_pos hgb]
  exact (spectralResolution A hA).integral_mul f g hf hg hfb hgb

/-- Uniform norm control on the real spectrum. -/
theorem norm_boundedBorelFunctionalCalculus_le
    (A : E →L[𝕜] E) (hA : IsSelfAdjointOperator A)
    (f : ℝ → ℝ) (hf : Measurable f) (C : ℝ) (hC0 : 0 ≤ C)
    (hC : ∀ x ∈ realSpectrum A, |f x| ≤ C) :
    ‖boundedBorelFunctionalCalculus A f‖ ≤ C := by
  have hfb : BoundedOnSpectrum A f := ⟨C, hC⟩
  unfold boundedBorelFunctionalCalculus
  rw [dif_pos hA, dif_pos hf, dif_pos hfb]
  exact (spectralResolution A hA).norm_integral_le f hf C hC0 hC

end DavisKahanExt
end ForMathlib
