/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/

import Spectra.QuantumMechanics.Channels.TraceClass.PartialIsometry

/-!
# Final-space identities for the bounded polar isometry

Spectra currently proves the initial projection identity
`U* U = P_(closure range |T|)`.  Nonacute direct rotations also need the
symmetric final projection identity
`U U* = P_(closure range T)`.  The argument below identifies the range of the
polar partial isometry with the closed range generated by `T`, then invokes
orthogonal-projection uniqueness.
-/

open scoped InnerProductSpace

namespace Spectra
namespace QuantumMechanics
namespace Channels

noncomputable section

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H]

/-- The final space in the bounded polar decomposition. -/
noncomputable def polarFinalRange (T : H →L[ℂ] H) : Submodule ℂ H :=
  (LinearMap.range T.toLinearMap).topologicalClosure

noncomputable instance polarFinalRange_hasOrthogonalProjection (T : H →L[ℂ] H) :
    (polarFinalRange T).HasOrthogonalProjection := by
  letI : CompleteSpace (polarFinalRange T) :=
    (Submodule.isClosed_topologicalClosure
      (LinearMap.range T.toLinearMap)).completeSpace_coe
  exact Submodule.HasOrthogonalProjection.ofCompleteSpace (polarFinalRange T)

/-- The range of the polar partial isometry lies in the final polar space. -/
theorem polarPartial_mem_finalRange (T : H →L[ℂ] H)
    (x : polarRange T) : polarPartial T x ∈ polarFinalRange T := by
  let M : Submodule ℂ (polarRange T) :=
    (polarPartial T).toLinearMap.ker
  have hdense : DenseRange (absOpCorestrict T) := denseRange_absOpCorestrict T
  have hclosed : IsClosed {x : polarRange T |
      polarPartial T x ∈ polarFinalRange T} := by
    exact (polarFinalRange T).isClosed.preimage (polarPartial T).continuous
  apply hclosed.eq_univ_of_dense
  intro x
  change polarPartial T (absOpCorestrict T x) ∈ polarFinalRange T
  rw [polarPartial_absOpCorestrict]
  exact Submodule.subset_topologicalClosure
    (LinearMap.mem_range_self T.toLinearMap x)

/-- The range of the polar partial isometry is dense in the final polar space. -/
theorem denseRange_polarPartial_final (T : H →L[ℂ] H) :
    DenseRange
      ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)) := by
  rw [DenseRange, dense_iff_closure_eq]
  apply Set.Subset.antisymm
  · exact Set.subset_univ _
  · intro y hy
    have hyAmbient : (y : H) ∈ closure (Set.range T) := by
      simpa [polarFinalRange, Submodule.topologicalClosure_coe,
        LinearMap.coe_range] using y.property
    have himage : Set.range T ⊆
        ((fun z : polarFinalRange T => (z : H)) ''
          Set.range ((polarPartial T).codRestrict (polarFinalRange T)
            (polarPartial_mem_finalRange T))) := by
      intro z hz
      rcases hz with ⟨x, rfl⟩
      refine ⟨⟨T x, Submodule.subset_topologicalClosure
        (LinearMap.mem_range_self T.toLinearMap x)⟩, ?_, rfl⟩
      refine ⟨absOpCorestrict T x, ?_⟩
      apply Subtype.ext
      exact polarPartial_absOpCorestrict T x
    have hclosedEmbedding : IsClosedEmbedding
        ((fun z : polarFinalRange T => (z : H))) :=
      IsClosedEmbedding.subtypeVal
        (Submodule.isClosed_topologicalClosure
          (LinearMap.range T.toLinearMap))
    have hyImage : (y : H) ∈ closure
        (((fun z : polarFinalRange T => (z : H)) ''
          Set.range ((polarPartial T).codRestrict (polarFinalRange T)
            (polarPartial_mem_finalRange T)))) :=
      closure_mono himage hyAmbient
    rw [hclosedEmbedding.closure_image_eq] at hyImage
    rcases hyImage with ⟨z, hz, hzy⟩
    simpa [Subtype.ext_iff] using hz

/-- The polar partial isometry, restricted to its final space, is onto. -/
theorem polarPartial_final_surjective (T : H →L[ℂ] H) :
    Function.Surjective
      ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)) := by
  let W : polarRange T →ₗᵢ[ℂ] polarFinalRange T :=
    { toLinearMap := ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)).toLinearMap
      norm_map' := fun x => by
        change ‖polarPartial T x‖ = ‖x‖
        exact norm_polarPartial_eq T x }
  have hclosed : IsClosed (Set.range W) := W.isClosed_range
  have hdense : DenseRange W := by
    simpa [W] using denseRange_polarPartial_final T
  rw [DenseRange, dense_iff_closure_eq, hclosed.closure_eq] at hdense
  exact Set.range_eq_univ.mp hdense

/-- The polar partial isometry as a unitary between its initial and final
spaces. -/
noncomputable def polarPartialFinalEquiv (T : H →L[ℂ] H) :
    polarRange T ≃ₗᵢ[ℂ] polarFinalRange T :=
  LinearIsometryEquiv.ofSurjective
    { toLinearMap := ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)).toLinearMap
      norm_map' := fun x => by
        change ‖polarPartial T x‖ = ‖x‖
        exact norm_polarPartial_eq T x }
    (polarPartial_final_surjective T)

/-- The final projection identity for the polar isometry. -/
theorem polarIsometry_comp_adjoint_self (T : H →L[ℂ] H) :
    polarIsometry T ∘L (polarIsometry T)† =
      (polarFinalRange T).starProjection := by
  let e := polarPartialFinalEquiv T
  refine ContinuousLinearMap.ext fun x => ?_
  obtain ⟨y, hy, r, hr, hxr⟩ :=
    Submodule.HasOrthogonalProjection.exists_orthogonal
      (K := polarFinalRange T) x
  have hprojY : (polarFinalRange T).starProjection y = y :=
    Submodule.starProjection_eq_self_iff.mpr hy
  have hprojR : (polarFinalRange T).starProjection r = 0 :=
    Submodule.starProjection_apply_eq_zero_iff.mpr hr
  have hUstarR : (polarIsometry T)† r = 0 := by
    refine ext_inner_right ℂ fun z => ?_
    rw [ContinuousLinearMap.adjoint_inner_left]
    have hzFinal : polarIsometry T z ∈ polarFinalRange T := by
      rw [polarIsometry_apply_eq]
      exact polarPartial_mem_finalRange T _
    exact hr (polarIsometry T z) hzFinal
  have hUstarY : (polarIsometry T)† y =
      ((polarRange T).subtypeL
        (e.symm ⟨y, hy⟩) : H) := by
    refine ext_inner_right ℂ fun z => ?_
    rw [ContinuousLinearMap.adjoint_inner_left]
    rw [polarIsometry_apply_eq]
    have hinner := LinearIsometry.inner_map_map e
      ((polarRange T).orthogonalProjection z) (e.symm ⟨y, hy⟩)
    simpa [e, polarPartialFinalEquiv, Submodule.coe_inner,
      ContinuousLinearMap.comp_apply] using hinner
  rw [hxr, map_add, map_add, hUstarR, add_zero,
    ContinuousLinearMap.comp_apply, hUstarY]
  have heval : polarIsometry T
      ((polarRange T).subtypeL (e.symm ⟨y, hy⟩) : H) = y := by
    rw [polarIsometry_apply_eq]
    have hproj : (polarRange T).orthogonalProjection
        ((polarRange T).subtypeL (e.symm ⟨y, hy⟩) : H) =
          e.symm ⟨y, hy⟩ := by
      apply Subtype.ext
      exact Submodule.starProjection_eq_self_iff.mpr
        (e.symm ⟨y, hy⟩).property
    rw [hproj]
    exact congrArg Subtype.val (e.apply_symm_apply ⟨y, hy⟩)
  rw [heval, hprojY, hprojR, map_add, add_zero]

/-- The adjoint polar isometry is the polar isometry of the adjoint. -/
theorem adjoint_polarIsometry (T : H →L[ℂ] H) :
    (polarIsometry T)† = polarIsometry (T†) := by
  let e := polarPartialFinalEquiv T
  refine ContinuousLinearMap.ext fun x => ?_
  obtain ⟨y, hy, r, hr, hxr⟩ :=
    Submodule.HasOrthogonalProjection.exists_orthogonal
      (K := polarFinalRange T) x
  have hstarR : (polarIsometry T)† r = 0 := by
    refine ext_inner_right ℂ fun z => ?_
    rw [ContinuousLinearMap.adjoint_inner_left]
    exact hr _ (polarPartial_mem_finalRange T
      ((polarRange T).orthogonalProjection z))
  have hAdjInitial : polarRange (T†) = polarFinalRange T := by
    rw [polarRange, polarFinalRange]
    exact closure_range_abs_adjoint_eq_closure_range
  rw [hxr, map_add, map_add, hstarR]
  have hrAdj : polarIsometry (T†) r = 0 := by
    rw [polarIsometry_apply_eq, hAdjInitial]
    rw [Submodule.orthogonalProjection_eq_zero_iff.mpr hr]
    simp
  rw [hrAdj, add_zero, add_zero]
  refine ext_inner_right ℂ fun z => ?_
  rw [ContinuousLinearMap.adjoint_inner_left]
  exact polar_partial_adjoint_formula T y hy z

end
end Channels
end QuantumMechanics
end Spectra
