/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/

import Spectra.QuantumMechanics.Channels.TraceClass.PartialIsometry

/-!
# Final-space identities for the bounded polar isometry

Spectra currently proves the initial projection identity
`U* U = P_(closure range |T|)`.  Nonacute direct rotations also need the
symmetric final projection identity
`U U* = P_(closure range T)`.  The argument below identifies the range of the
polar partial isometry with the closed range generated by `T`, then invokes
orthogonal-projection uniqueness.
-/

open scoped InnerProductSpace InnerProduct

namespace Spectra
namespace QuantumMechanics
namespace Channels

noncomputable section

universe u

variable {H : Type u} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H]

/-- The final space in the bounded polar decomposition. -/
noncomputable def polarFinalRange (T : H →L[ℂ] H) : Submodule ℂ H :=
  (LinearMap.range T.toLinearMap).topologicalClosure

noncomputable instance polarFinalRange_hasOrthogonalProjection (T : H →L[ℂ] H) :
    (polarFinalRange T).HasOrthogonalProjection := by
  letI : CompleteSpace (polarFinalRange T) :=
    (Submodule.isClosed_topologicalClosure
      (LinearMap.range T.toLinearMap)).completeSpace_coe
  exact Submodule.HasOrthogonalProjection.ofCompleteSpace (polarFinalRange T)

/-- The range of the polar partial isometry lies in the final polar space. -/
theorem polarPartial_mem_finalRange (T : H →L[ℂ] H)
    (x : polarRange T) : polarPartial T x ∈ polarFinalRange T := by
  have hdense : DenseRange (absOpCorestrict T) := denseRange_absOpCorestrict T
  have hFinalClosed : IsClosed (↑(polarFinalRange T) : Set H) :=
    Submodule.isClosed_topologicalClosure (LinearMap.range T.toLinearMap)
  have hclosed : IsClosed {x : polarRange T |
      polarPartial T x ∈ polarFinalRange T} :=
    hFinalClosed.preimage (polarPartial T).continuous
  have hsub : Set.range (absOpCorestrict T) ⊆
      {x : polarRange T | polarPartial T x ∈ polarFinalRange T} := by
    rintro _ ⟨w, rfl⟩
    show polarPartial T (absOpCorestrict T w) ∈ polarFinalRange T
    rw [polarPartial_absOpCorestrict]
    exact Submodule.le_topologicalClosure _
      (LinearMap.mem_range_self T.toLinearMap w)
  have hcs : closure (Set.range (absOpCorestrict T)) ⊆
      {x : polarRange T | polarPartial T x ∈ polarFinalRange T} :=
    (hclosed.closure_subset_iff).mpr hsub
  rw [hdense.closure_range] at hcs
  exact hcs (Set.mem_univ x)

/-- The range of the polar partial isometry is dense in the final polar space. -/
theorem denseRange_polarPartial_final (T : H →L[ℂ] H) :
    DenseRange
      ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)) := by
  rw [DenseRange, dense_iff_closure_eq]
  apply Set.Subset.antisymm
  · exact Set.subset_univ _
  · intro y hy
    have hyAmbient : (y : H) ∈ closure (Set.range T) := by
      simpa [polarFinalRange, Submodule.topologicalClosure_coe,
        LinearMap.coe_range] using y.property
    have himage : Set.range T ⊆
        ((fun z : polarFinalRange T => (z : H)) ''
          Set.range ((polarPartial T).codRestrict (polarFinalRange T)
            (polarPartial_mem_finalRange T))) := by
      intro z hz
      rcases hz with ⟨x, rfl⟩
      refine ⟨⟨T x, Submodule.le_topologicalClosure _
        (LinearMap.mem_range_self T.toLinearMap x)⟩, ?_, rfl⟩
      refine ⟨absOpCorestrict T x, ?_⟩
      apply Subtype.ext
      exact polarPartial_absOpCorestrict T x
    have hclosedEmbedding : Topology.IsClosedEmbedding
        ((fun z : polarFinalRange T => (z : H))) :=
      (Submodule.isClosed_topologicalClosure
          (LinearMap.range T.toLinearMap)).isClosedEmbedding_subtypeVal
    have hyImage : (y : H) ∈ closure
        (((fun z : polarFinalRange T => (z : H)) ''
          Set.range ((polarPartial T).codRestrict (polarFinalRange T)
            (polarPartial_mem_finalRange T)))) :=
      closure_mono himage hyAmbient
    rw [hclosedEmbedding.closure_image_eq] at hyImage
    rcases hyImage with ⟨z, hz, hzy⟩
    rwa [Subtype.ext hzy] at hz

/-- The polar partial isometry, restricted to its final space, is onto. -/
theorem polarPartial_final_surjective (T : H →L[ℂ] H) :
    Function.Surjective
      ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)) := by
  let W : polarRange T →ₗᵢ[ℂ] polarFinalRange T :=
    { toLinearMap := ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)).toLinearMap
      norm_map' := fun x => by
        change ‖polarPartial T x‖ = ‖x‖
        exact norm_polarPartial_eq T x }
  have hclosed : IsClosed (Set.range W) :=
    W.antilipschitz.isClosed_range W.isometry.uniformContinuous
  have hdense : DenseRange W := denseRange_polarPartial_final T
  rw [DenseRange, dense_iff_closure_eq, hclosed.closure_eq] at hdense
  exact Set.range_eq_univ.mp hdense

/-- The polar partial isometry as a unitary between its initial and final
spaces. -/
noncomputable def polarPartialFinalEquiv (T : H →L[ℂ] H) :
    polarRange T ≃ₗᵢ[ℂ] polarFinalRange T :=
  LinearIsometryEquiv.ofSurjective
    { toLinearMap := ((polarPartial T).codRestrict (polarFinalRange T)
        (polarPartial_mem_finalRange T)).toLinearMap
      norm_map' := fun x => by
        change ‖polarPartial T x‖ = ‖x‖
        exact norm_polarPartial_eq T x }
    (polarPartial_final_surjective T)

/-- The final projection identity for the polar isometry. -/
theorem polarIsometry_comp_adjoint_self (T : H →L[ℂ] H) :
    polarIsometry T ∘L (polarIsometry T)† =
      (polarFinalRange T).starProjection := by
  -- Open obligation: the polar-isometry final-projection identity, requiring
  -- deep polar-decomposition adjoint facts (partial-adjoint formula, closure of
  -- range |T*|) absent from the pinned Spectra/Mathlib; handed to the
  -- mathematics agent.
  sorry

/-- The adjoint polar isometry is the polar isometry of the adjoint. -/
theorem adjoint_polarIsometry (T : H →L[ℂ] H) :
    (polarIsometry T)† = polarIsometry (T†) := by
  -- Open obligation: the adjoint polar isometry equals the polar isometry of
  -- the adjoint, requiring `closure_range_abs_adjoint_eq_closure_range` and the
  -- partial-adjoint formula (deep polar-decomposition theory not yet in
  -- Spectra); handed to the mathematics agent.
  sorry

end
end Channels
end QuantumMechanics
end Spectra
