#!/usr/bin/env python3
"""Build paper-local views of the Yu--Wang--Samworth source census.

The repository census is keyed on the published source, not on the Lean tree.
This script makes its meaning visible to paper readers: the 24 entries are a
mixture of theorem/lemma/equation/example/definition/exposition rows, and the
census also deliberately records corrections and non-source extensions so they
cannot be mistaken for claims of the printed paper.
"""

from __future__ import annotations

import collections
import csv
import json
import pathlib
import subprocess

from accounting_lib import latex_escape

HERE = pathlib.Path(__file__).resolve().parent
PAPER = HERE.parent
GENERATED = PAPER / "generated"
ROOT = pathlib.Path(subprocess.check_output(["git", "rev-parse", "--show-toplevel"], cwd=PAPER, text=True).strip())
CENSUS = ROOT / "dev/yu-wang-samworth-2015-full-source-census.json"

# These rows say in their census metadata that they are additions beyond the
# printed paper. Keep the classification explicit instead of inferring it from
# prose every time the paper is rebuilt.
NON_SOURCE_ADDITIONS = {
    "YWS-T3-rankone": "application-oriented extension beyond the printed paper",
    "YWS-A-dilation-alternative": "modern alternative proof route, not the paper's route",
}


def write_csv(path: pathlib.Path, rows: list[dict], fieldnames: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames, extrasaction="ignore")
        w.writeheader()
        w.writerows(rows)


def main() -> None:
    data = json.loads(CENSUS.read_text(encoding="utf-8"))
    items = data["items"]
    GENERATED.mkdir(parents=True, exist_ok=True)

    rows: list[dict] = []
    for index, item in enumerate(items, 1):
        relation = "paper_source"
        relation_note = ""
        if item["id"] in NON_SOURCE_ADDITIONS:
            relation = "explicit_non_source_addition"
            relation_note = NON_SOURCE_ADDITIONS[item["id"]]
        rows.append(
            {
                "index": index,
                "id": item["id"],
                "section": item.get("section", ""),
                "source_kind": item.get("source_kind", ""),
                "source_anchor": item.get("source_anchor", ""),
                "title": item.get("title", ""),
                "source_relation": relation,
                "source_relation_note": relation_note,
                "status": item.get("status", ""),
                "verification": item.get("verification", ""),
                "importance": item.get("importance", ""),
                "declaration_count": len(item.get("lean_declarations", [])),
                "lean_declarations": " | ".join(item.get("lean_declarations", [])),
                "gap_refs": " | ".join(item.get("gap_refs", [])),
            }
        )
    write_csv(GENERATED / "yws_census_items.csv", rows, list(rows[0]))

    kind_counts = collections.Counter(r["source_kind"] for r in rows)
    kind_rows = [{"source_kind": k, "entries": n} for k, n in sorted(kind_counts.items(), key=lambda kv: (-kv[1], kv[0]))]
    write_csv(GENERATED / "yws_census_by_kind.csv", kind_rows, ["source_kind", "entries"])

    status_counts = collections.Counter(r["status"] for r in rows)
    verified = sum(r["verification"] == "proved_in_build" for r in rows)
    source_rows = sum(r["source_relation"] == "paper_source" for r in rows)
    extra_rows = len(rows) - source_rows
    corrected_rows = status_counts.get("compiled_corrected", 0)

    macros = [
        "% Generated by scripts/build_source_census.py; do not edit by hand.",
        f"\\newcommand{{\\YWSCensusEntryCount}}{{{len(rows)}}}",
        f"\\newcommand{{\\YWSCensusPaperSourceCount}}{{{source_rows}}}",
        f"\\newcommand{{\\YWSCensusExplicitAdditionCount}}{{{extra_rows}}}",
        f"\\newcommand{{\\YWSCensusVerifiedCount}}{{{verified}}}",
        f"\\newcommand{{\\YWSCensusCorrectedCount}}{{{corrected_rows}}}",
    ]
    (GENERATED / "census_macros.tex").write_text("\n".join(macros) + "\n", encoding="utf-8")

    lines = [
        "% Generated by scripts/build_source_census.py; do not edit by hand.",
        "\\begin{tabular}{lr}",
        "\\toprule",
        "Census row kind & Entries \\\\",
        "\\midrule",
    ]
    pretty = {
        "theorem": "Theorem/conclusion",
        "lemma": "Lemma",
        "example": "Example",
        "identity": "Identity",
        "equation": "Numbered equation",
        "corollary": "Corollary",
        "exposition": "Exposition/audit route",
        "definition": "Definition",
        "scope": "Source convention/scope",
    }
    for r in kind_rows:
        lines.append(f"{latex_escape(pretty.get(r['source_kind'], r['source_kind']))} & {r['entries']} \\\\")
    lines += ["\\midrule", f"Total & {len(rows)} \\\\" , "\\bottomrule", "\\end{tabular}"]
    (GENERATED / "yws_census_kind_table.tex").write_text("\n".join(lines) + "\n", encoding="utf-8")

    report = [
        "# YWS source-census report",
        "",
        f"The repository census contains **{len(rows)} tracking entries**. It is keyed on the published paper rather than the Lean tree.",
        f"Of these, **{source_rows}** are classified here as paper-source rows and **{extra_rows}** are explicitly marked additions beyond the printed paper.",
        f"All **{verified}** entries currently have `verification=proved_in_build`; this is a build-verification field, not a claim that every row is a verbatim theorem statement.",
        f"**{corrected_rows}** rows have `status=compiled_corrected`; several rows can share the same underlying source defect, so this is not a defect count.",
        "",
        "## What the rows count",
        "",
    ]
    for r in kind_rows:
        report.append(f"- `{r['source_kind']}`: **{r['entries']}**")
    report += [
        "",
        "## Explicit non-source additions",
        "",
    ]
    for row in rows:
        if row["source_relation"] == "explicit_non_source_addition":
            report.append(f"- `{row['id']}`: {row['source_relation_note']}")
    report += [
        "",
        "## Interpretation",
        "",
        "The census is a progress/audit instrument. A row may correspond to a theorem conclusion, an equation, an example, a source convention, or an explicitly recorded extension. The full row-level inventory is `generated/yws_census_items.csv`.",
    ]
    (GENERATED / "CENSUS_REPORT.md").write_text("\n".join(report) + "\n", encoding="utf-8")

    print(f"census: {len(rows)} entries, {verified} proved_in_build, {extra_rows} explicit non-source additions")


if __name__ == "__main__":
    main()
