import DavisKahan.Experimental.Scratch.Section4.InfiniteIdealDominance
import DavisKahan.Experimental.Scratch.Section4.FiniteSourceSurface

import DavisKahan.Experimental.Scratch.Section4.InfiniteProposition41
