#!/usr/bin/env python3
"""Check the experimental recursive hidden-foundation map.

The default mode is static and does not require Lean.  ``--lean-probe`` adds
module-local ``#check`` probes when a Lean toolchain is available.
"""
from __future__ import annotations

import argparse
import json
import re
import subprocess
import tempfile
from collections import Counter, defaultdict, deque
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MANIFEST = REPO / "dev" / "davis-kahan-hidden-foundations.json"
REPORT = REPO / "dev" / "davis-kahan-hidden-foundations-status.md"

DECL_RE = re.compile(
    r"^\s*(?:noncomputable\s+)?(?:def|abbrev|theorem|lemma|structure|class)\s+([A-Za-z0-9_\.]+)",
    re.MULTILINE,
)
ESCAPE_TOKENS = ["sor" + "ry", "ad" + "mit", "native" + "_decide", "ax" + "iom"]


def load_manifest() -> dict:
    return json.loads(MANIFEST.read_text())


def declaration_present(node: dict) -> bool:
    path = REPO / node["file"]
    if not path.exists():
        return False
    wanted = node["declaration"].split(".")[-1]
    found = DECL_RE.findall(path.read_text())
    return any(name == wanted or name.endswith("." + wanted) for name in found)


def scan_escape_markers() -> list[tuple[str, int, str]]:
    root = REPO / "DavisKahan" / "Experimental" / "MathAhead" / "HiddenFoundations"
    findings: list[tuple[str, int, str]] = []
    for path in sorted(root.glob("*.lean")):
        for lineno, line in enumerate(path.read_text().splitlines(), 1):
            for token in ESCAPE_TOKENS:
                if re.search(rf"\b{re.escape(token)}\b", line):
                    findings.append((str(path.relative_to(REPO)), lineno, token))
    return findings


def graph_status(nodes: list[dict]) -> tuple[list[str], list[list[str]]]:
    ids = {n["id"] for n in nodes}
    missing = sorted({d for n in nodes for d in n.get("dependencies", []) if d not in ids})
    outgoing: dict[str, list[str]] = defaultdict(list)
    indeg = Counter({n["id"]: 0 for n in nodes})
    for n in nodes:
        for dep in n.get("dependencies", []):
            if dep in ids:
                outgoing[dep].append(n["id"])
                indeg[n["id"]] += 1
    q = deque(sorted(k for k, v in indeg.items() if v == 0))
    seen: list[str] = []
    while q:
        x = q.popleft()
        seen.append(x)
        for y in outgoing[x]:
            indeg[y] -= 1
            if indeg[y] == 0:
                q.append(y)
    cycles: list[list[str]] = []
    if len(seen) != len(nodes):
        cycles.append(sorted(k for k, v in indeg.items() if v > 0))
    return missing, cycles


def lean_probe(nodes: list[dict]) -> dict[str, bool | None]:
    by_module: dict[str, list[dict]] = defaultdict(list)
    for node in nodes:
        by_module[node["module"]].append(node)
    result: dict[str, bool | None] = {n["id"]: None for n in nodes}
    for module, group in sorted(by_module.items()):
        source = [f"import {module}", ""]
        source.extend(f"#check {n['declaration']}" for n in group)
        with tempfile.NamedTemporaryFile("w", suffix=".lean", dir=REPO, delete=False) as f:
            f.write("\n".join(source) + "\n")
            tmp = Path(f.name)
        try:
            proc = subprocess.run(
                ["lake", "env", "lean", str(tmp.relative_to(REPO))],
                cwd=REPO,
                text=True,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                timeout=180,
            )
            ok = proc.returncode == 0
            for n in group:
                result[n["id"]] = ok
        except (FileNotFoundError, subprocess.TimeoutExpired):
            for n in group:
                result[n["id"]] = None
        finally:
            tmp.unlink(missing_ok=True)
    return result


def render_report(data: dict, present: dict[str, bool], probes: dict[str, bool | None],
                  missing_deps: list[str], cycles: list[list[str]], escapes: list[tuple[str, int, str]]) -> str:
    nodes = data["nodes"]
    kinds = Counter(n["kind"] for n in nodes)
    lines = [
        "# Davis--Kahan hidden-foundation status",
        "",
        "Generated by `scripts/check_davis_kahan_hidden_foundations.py`.",
        "",
        "## Summary",
        "",
        f"- Tracked hidden-foundation nodes: **{len(nodes)}**",
        f"- Textually present declarations: **{sum(present.values())}/{len(nodes)}**",
        f"- Full-proof candidates: **{kinds['proof_candidate']}**",
        f"- Concrete constructions: **{kinds['construction']}**",
        f"- Existing-layer bridges: **{kinds['bridge']}**",
        f"- Explicit unresolved-foundation interfaces: **{kinds['interface']}**",
        f"- Missing internal dependency identifiers: **{len(missing_deps)}**",
        f"- Dependency cycles: **{len(cycles)}**",
        f"- Proof-escape markers in hidden Lean files: **{len(escapes)}**",
        "",
        "Interface nodes are deliberately not counted as completed mathematics.  They expose the exact analytic theorem package that must still be constructed.",
        "",
    ]
    if any(v is not None for v in probes.values()):
        yes = sum(v is True for v in probes.values())
        no = sum(v is False for v in probes.values())
        lines += [f"- Lean probes: **{yes} successful**, **{no} failed**", ""]

    lines += [
        "## Campaigns",
        "",
    ]
    by_id = {n["id"]: n for n in nodes}
    for campaign in data.get("campaigns", []):
        c_nodes = [by_id[x] for x in campaign["nodes"]]
        lines.append(f"### {campaign['title']}")
        lines.append("")
        lines.append(f"Tracked nodes: **{len(c_nodes)}**; interfaces: **{sum(n['kind']=='interface' for n in c_nodes)}**.")
        lines.append("")

    lines += [
        "## Nodes",
        "",
        "| Node | Kind | Confidence | Text | Lean | Frontier alignment |",
        "|---|---|---:|:---:|:---:|---|",
    ]
    for n in nodes:
        probe = probes.get(n["id"])
        lean = "yes" if probe is True else "no" if probe is False else "-"
        frontier = ", ".join(f"`{x}`" for x in n.get("frontier_nodes", [])) or "-"
        lines.append(
            f"| `{n['id']}` | {n['kind']} | {n['confidence']} | "
            f"{'yes' if present[n['id']] else 'no'} | {lean} | {frontier} |"
        )

    lines += ["", "## Dependency graph", ""]
    for n in nodes:
        deps = ", ".join(f"`{d}`" for d in n.get("dependencies", [])) or "(root)"
        lines.append(f"- `{n['id']}` <- {deps}")

    if missing_deps:
        lines += ["", "## Missing dependency identifiers", ""]
        lines.extend(f"- `{x}`" for x in missing_deps)
    if cycles:
        lines += ["", "## Dependency cycles", ""]
        for cycle in cycles:
            lines.append("- " + ", ".join(f"`{x}`" for x in cycle))
    if escapes:
        lines += ["", "## Proof-escape marker findings", ""]
        for path, lineno, token in escapes:
            lines.append(f"- `{path}:{lineno}`: `{token}`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write-report", action="store_true")
    parser.add_argument("--lean-probe", action="store_true")
    args = parser.parse_args()

    data = load_manifest()
    nodes = data["nodes"]
    present = {n["id"]: declaration_present(n) for n in nodes}
    missing_deps, cycles = graph_status(nodes)
    escapes = scan_escape_markers()
    probes = lean_probe(nodes) if args.lean_probe else {n["id"]: None for n in nodes}
    report = render_report(data, present, probes, missing_deps, cycles, escapes)
    if args.write_report:
        REPORT.write_text(report)
    print(report)
    return 1 if (not all(present.values()) or missing_deps or cycles or escapes or any(v is False for v in probes.values())) else 0


if __name__ == "__main__":
    raise SystemExit(main())
