name = "finish_tan_two_theta"
version = "0.2.0"
defaultTargets = ["FinishTanTwoTheta"]

[leanOptions]
pp.unicode.fun = true
autoImplicit = false

[[require]]
name = "aiq_dkps_formalization"
path = ".."

[[lean_lib]]
name = "FinishTanTwoTheta"
globs = ["FinishTanTwoTheta.*"]
