/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/
import FinishTanTwoTheta.OperatorIdeal.StandardSymmetricIdeal
import DavisKahan.OperatorIdeal.ApproximationNumbers.ScalarGeneric

/-!
# Operator ideals generated by symmetric norming functions

Every coherent symmetric norming function has two classical operator ideals:
its maximal/Fatou ideal and its minimal finite-rank closure.  This file builds
both as `SymmetricOperatorIdealFamily`s.  Combined with the preceding file, it
proves Fan dominance for every ideal obtained by the standard symmetric
norming-function construction, rather than assuming dominance separately for
each example.
-/

namespace TauCeti
namespace FinishTanTwoTheta

open scoped ENNReal Topology

universe u v

variable {𝕜 : Type u} [RCLike 𝕜]

/-- Extended operator gauge generated from a symmetric norming function and a
classical completion mode. -/
noncomputable def generatedIdealGauge
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A : E →L[𝕜] F) : ℝ≥0∞ :=
  Φ.standardSequenceGauge mode (approximationNumberSequence A)

/-- The first coordinate is dominated by every normalized finite symmetric
gauge.  This supplies the operator-norm domination axiom. -/
theorem approximationNumber_zero_le_generatedGauge
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A : E →L[𝕜] F) :
    ENNReal.ofReal (A.approximationNumber 0) ≤
      generatedIdealGauge (𝕜 := 𝕜) Φ mode A := by
  unfold generatedIdealGauge
  exact Φ.firstCoordinate_le_standardSequenceGauge mode
    (approximationNumberSequence A)
    (A.approximationNumber_nonneg 0)

/-- Generated gauges are subadditive. -/
theorem generatedIdealGauge_add_le
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A B : E →L[𝕜] F) :
    generatedIdealGauge (𝕜 := 𝕜) Φ mode (A + B) ≤
      generatedIdealGauge (𝕜 := 𝕜) Φ mode A +
        generatedIdealGauge (𝕜 := 𝕜) Φ mode B := by
  unfold generatedIdealGauge
  let a := approximationNumberSequence A
  let b := approximationNumberSequence B
  let c := approximationNumberSequence (A + B)
  have hc : WeaklySubmajorized c (a + b) := by
    obtain ⟨hca, hcn⟩ := approximationNumberSequence_antitone_nonneg (A + B)
    obtain ⟨haa, han⟩ := approximationNumberSequence_antitone_nonneg A
    obtain ⟨hba, hbn⟩ := approximationNumberSequence_antitone_nonneg B
    refine ⟨hca, ?_, hcn, ?_, ?_⟩
    · intro i j hij
      exact add_le_add (haa hij) (hba hij)
    · intro n
      exact add_nonneg (han n) (hbn n)
    · intro k
      simpa [a, b, c, approximationNumberPrefix, sequencePrefixSum,
        approximationNumberSequence, kyFanApproximationGauge,
        approximationSingularValue] using
        (kyFanApproximationGauge_add_le k A B)
  calc
    Φ.standardSequenceGauge mode c
        ≤ Φ.standardSequenceGauge mode (a + b) :=
      Φ.standardSequenceGauge_mono_of_weaklySubmajorized mode hc
    _ ≤ Φ.standardSequenceGauge mode a +
          Φ.standardSequenceGauge mode b :=
      Φ.standardSequenceGauge_add_le mode a b

/-- Generated gauges are absolutely homogeneous. -/
theorem generatedIdealGauge_smul
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (c : 𝕜) (A : E →L[𝕜] F) :
    generatedIdealGauge (𝕜 := 𝕜) Φ mode (c • A) =
      ‖c‖ₑ * generatedIdealGauge (𝕜 := 𝕜) Φ mode A := by
  unfold generatedIdealGauge
  have hseq : approximationNumberSequence (c • A) =
      ‖c‖ • approximationNumberSequence A := by
    funext n
    simp [approximationNumberSequence]
  rw [hseq, Φ.standardSequenceGauge_smul mode (norm_nonneg c)]
  simp [ofReal_norm]

/-- Two-sided ideal inequality for generated gauges. -/
theorem generatedIdealGauge_comp_le
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E H : Type v} {F G : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    [NormedAddCommGroup G] [InnerProductSpace 𝕜 G] [CompleteSpace G]
    [NormedAddCommGroup H] [InnerProductSpace 𝕜 H] [CompleteSpace H]
    (L : F →L[𝕜] G) (A : E →L[𝕜] F) (R : H →L[𝕜] E) :
    generatedIdealGauge (𝕜 := 𝕜) Φ mode (L ∘L A ∘L R) ≤
      ‖L‖ₑ * generatedIdealGauge (𝕜 := 𝕜) Φ mode A * ‖R‖ₑ := by
  unfold generatedIdealGauge
  let c : ℝ := ‖L‖ * ‖R‖
  have hc : 0 ≤ c := mul_nonneg (norm_nonneg L) (norm_nonneg R)
  have hpoint : ∀ n,
      approximationNumberSequence (L ∘L A ∘L R) n ≤
        (c • approximationNumberSequence A) n := by
    intro n
    simpa [c, approximationNumberSequence, mul_assoc] using
      (ContinuousLinearMap.approximationNumber_comp_comp_le L A R n)
  have hweak : WeaklySubmajorized
      (approximationNumberSequence (L ∘L A ∘L R))
      (c • approximationNumberSequence A) := by
    obtain ⟨hxa, hxn⟩ :=
      approximationNumberSequence_antitone_nonneg (L ∘L A ∘L R)
    obtain ⟨haa, han⟩ := approximationNumberSequence_antitone_nonneg A
    exact WeaklySubmajorized.of_pointwise hxa
      (fun _ _ h => mul_le_mul_of_nonneg_left (haa h) hc) hxn
      (fun n => mul_nonneg hc (han n)) hpoint
  calc
    Φ.standardSequenceGauge mode
        (approximationNumberSequence (L ∘L A ∘L R))
        ≤ Φ.standardSequenceGauge mode
            (c • approximationNumberSequence A) :=
      Φ.standardSequenceGauge_mono_of_weaklySubmajorized mode hweak
    _ = ENNReal.ofReal c * Φ.standardSequenceGauge mode
          (approximationNumberSequence A) :=
      Φ.standardSequenceGauge_smul mode hc
    _ = ‖L‖ₑ * Φ.standardSequenceGauge mode
          (approximationNumberSequence A) * ‖R‖ₑ := by
      simp [c, ENNReal.ofReal_mul (norm_nonneg L), ofReal_norm, mul_assoc]

/-- Generated gauges are invariant under adjoint. -/
theorem generatedIdealGauge_adjoint
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A : E →L[𝕜] F) :
    generatedIdealGauge (𝕜 := 𝕜) Φ mode A.adjoint =
      generatedIdealGauge (𝕜 := 𝕜) Φ mode A := by
  unfold generatedIdealGauge
  congr 1
  funext n
  exact A.approximationNumber_adjoint n

/-- The symmetric operator ideal generated by `Φ` in either classical
completion. -/
noncomputable def generatedSymmetricIdealFamily
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion) :
    SymmetricOperatorIdealFamily.{u, v} 𝕜 where
  gauge := fun A => generatedIdealGauge Φ mode A
  gauge_add_le := generatedIdealGauge_add_le Φ mode
  gauge_smul := generatedIdealGauge_smul Φ mode
  enorm_le_gauge := by
    intro E F _ _ _ _ A
    rw [← ofReal_norm, ← A.approximationNumber_index_zero]
    exact approximationNumber_zero_le_generatedGauge Φ mode A
  gauge_comp_le := generatedIdealGauge_comp_le Φ mode
  gauge_adjoint := generatedIdealGauge_adjoint Φ mode

/-- Every norming function canonically produces a standard maximal ideal. -/
noncomputable def generatedMaximalStandardIdeal
    (Φ : SymmetricNormingFunction) : StandardSymmetricIdealFamily.{u, v} 𝕜 where
  toSymmetricOperatorIdealFamily :=
    generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .maximal
  normingFunction := Φ
  completion := .maximal
  gauge_eq_standardSequenceGauge := by intros; rfl

/-- Every norming function canonically produces a standard minimal ideal. -/
noncomputable def generatedMinimalStandardIdeal
    (Φ : SymmetricNormingFunction) : StandardSymmetricIdealFamily.{u, v} 𝕜 where
  toSymmetricOperatorIdealFamily :=
    generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .minimal
  normingFunction := Φ
  completion := .minimal
  gauge_eq_standardSequenceGauge := by intros; rfl

/-- Fan dominance for the maximal ideal generated by any symmetric norming
function. -/
theorem generatedMaximal_fanDominance
    (Φ : SymmetricNormingFunction)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A B : E →L[𝕜] F)
    (hB : B ∈ (generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .maximal)
      .toOperatorIdealFamily.carrier)
    (hprefix : ∀ k, approximationNumberPrefix k A ≤ approximationNumberPrefix k B) :
    A ∈ (generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .maximal)
      .toOperatorIdealFamily.carrier ∧
    generatedIdealGauge (𝕜 := 𝕜) Φ .maximal A ≤
      generatedIdealGauge (𝕜 := 𝕜) Φ .maximal B :=
  (generatedMaximalStandardIdeal (𝕜 := 𝕜) (v := v) Φ).fanDominance A B hB hprefix

/-- Fan dominance for the minimal ideal generated by any symmetric norming
function. -/
theorem generatedMinimal_fanDominance
    (Φ : SymmetricNormingFunction)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A B : E →L[𝕜] F)
    (hB : B ∈ (generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .minimal)
      .toOperatorIdealFamily.carrier)
    (hprefix : ∀ k, approximationNumberPrefix k A ≤ approximationNumberPrefix k B) :
    A ∈ (generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .minimal)
      .toOperatorIdealFamily.carrier ∧
    generatedIdealGauge (𝕜 := 𝕜) Φ .minimal A ≤
      generatedIdealGauge (𝕜 := 𝕜) Φ .minimal B :=
  (generatedMinimalStandardIdeal (𝕜 := 𝕜) (v := v) Φ).fanDominance A B hB hprefix

end FinishTanTwoTheta
end TauCeti
