/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/
import FinishTanTwoTheta.OperatorIdeal.StandardSymmetricIdeal
import DavisKahan.OperatorIdeal.ApproximationNumbers.ScalarGeneric

/-!
# Operator ideals generated by symmetric norming functions

Every coherent symmetric norming function has two classical operator ideals:
its maximal/Fatou ideal and its minimal finite-rank closure.  This file builds
both as `SymmetricOperatorIdealFamily`s.  Combined with the preceding file, it
proves Fan dominance for every ideal obtained by the standard symmetric
norming-function construction, rather than assuming dominance separately for
each example.
-/

namespace TauCeti
namespace FinishTanTwoTheta

open scoped ENNReal Topology

universe u v

variable {𝕜 : Type u} [RCLike 𝕜]

/-- Extended operator gauge generated from a symmetric norming function and a
classical completion mode. -/
noncomputable def generatedIdealGauge
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A : E →L[𝕜] F) : ℝ≥0∞ :=
  Φ.standardSequenceGauge mode (approximationNumberSequence A)

/-- The first coordinate is dominated by every normalized finite symmetric
gauge.  This supplies the operator-norm domination axiom. -/
theorem approximationNumber_zero_le_generatedGauge
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A : E →L[𝕜] F) :
    ENNReal.ofReal (A.approximationNumber 0) ≤
      generatedIdealGauge (𝕜 := 𝕜) Φ mode A := by
  /-
  On a member, apply finite-gauge monotonicity to the one-coordinate vector
  `(a_0)` and normalization.  Off the minimal carrier the right side is `∞`.
  -/
  sorry

/-- Generated gauges are subadditive. -/
theorem generatedIdealGauge_add_le
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A B : E →L[𝕜] F) :
    generatedIdealGauge (𝕜 := 𝕜) Φ mode (A + B) ≤
      generatedIdealGauge (𝕜 := 𝕜) Φ mode A +
        generatedIdealGauge (𝕜 := 𝕜) Φ mode B := by
  /-
  The approximation-number sequence of `A+B` is weakly submajorized by the
  pointwise sum of those of `A` and `B` (Ky Fan addition inequality).  Apply
  Fan monotonicity and the finite-gauge triangle inequality at every prefix.
  For the minimal completion, also show that the sum of two vanishing tails
  has vanishing tail.
  -/
  sorry

/-- Generated gauges are absolutely homogeneous. -/
theorem generatedIdealGauge_smul
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (c : 𝕜) (A : E →L[𝕜] F) :
    generatedIdealGauge (𝕜 := 𝕜) Φ mode (c • A) =
      ‖c‖ₑ * generatedIdealGauge (𝕜 := 𝕜) Φ mode A := by
  /- Approximation numbers scale by `||c||`.  For `c != 0`, minimal tail
  membership is equivalent before and after scaling; `c=0` is immediate. -/
  sorry

/-- Two-sided ideal inequality for generated gauges. -/
theorem generatedIdealGauge_comp_le
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E H : Type v} {F G : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    [NormedAddCommGroup G] [InnerProductSpace 𝕜 G] [CompleteSpace G]
    [NormedAddCommGroup H] [InnerProductSpace 𝕜 H] [CompleteSpace H]
    (L : F →L[𝕜] G) (A : E →L[𝕜] F) (R : H →L[𝕜] E) :
    generatedIdealGauge (𝕜 := 𝕜) Φ mode (L ∘L A ∘L R) ≤
      ‖L‖ₑ * generatedIdealGauge (𝕜 := 𝕜) Φ mode A * ‖R‖ₑ := by
  /-
  Use `a_n(LAR) <= ||L|| a_n(A) ||R||` coordinatewise, finite symmetric-gauge
  monotonicity, and homogeneity.  The same estimate sends vanishing tails to
  vanishing tails in the minimal completion.
  -/
  sorry

/-- Generated gauges are invariant under adjoint. -/
theorem generatedIdealGauge_adjoint
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A : E →L[𝕜] F) :
    generatedIdealGauge (𝕜 := 𝕜) Φ mode A.adjoint =
      generatedIdealGauge (𝕜 := 𝕜) Φ mode A := by
  /- Approximation numbers agree termwise under adjoint. -/
  sorry

/-- The symmetric operator ideal generated by `Φ` in either classical
completion. -/
noncomputable def generatedSymmetricIdealFamily
    (Φ : SymmetricNormingFunction) (mode : SymmetricIdealCompletion) :
    SymmetricOperatorIdealFamily.{u, v} 𝕜 where
  gauge := fun A => generatedIdealGauge Φ mode A
  gauge_add_le := generatedIdealGauge_add_le Φ mode
  gauge_smul := generatedIdealGauge_smul Φ mode
  enorm_le_gauge := by
    intro E F _ _ _ _ A
    rw [← ofReal_norm, ← A.approximationNumber_index_zero]
    exact approximationNumber_zero_le_generatedGauge Φ mode A
  gauge_comp_le := generatedIdealGauge_comp_le Φ mode
  gauge_adjoint := generatedIdealGauge_adjoint Φ mode

/-- Every norming function canonically produces a standard maximal ideal. -/
noncomputable def generatedMaximalStandardIdeal
    (Φ : SymmetricNormingFunction) : StandardSymmetricIdealFamily.{u, v} 𝕜 where
  toSymmetricOperatorIdealFamily :=
    generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .maximal
  normingFunction := Φ
  completion := .maximal
  gauge_eq_standardSequenceGauge := by intros; rfl

/-- Every norming function canonically produces a standard minimal ideal. -/
noncomputable def generatedMinimalStandardIdeal
    (Φ : SymmetricNormingFunction) : StandardSymmetricIdealFamily.{u, v} 𝕜 where
  toSymmetricOperatorIdealFamily :=
    generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .minimal
  normingFunction := Φ
  completion := .minimal
  gauge_eq_standardSequenceGauge := by intros; rfl

/-- Fan dominance for the maximal ideal generated by any symmetric norming
function. -/
theorem generatedMaximal_fanDominance
    (Φ : SymmetricNormingFunction)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A B : E →L[𝕜] F)
    (hB : B ∈ (generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .maximal)
      .toOperatorIdealFamily.carrier)
    (hprefix : ∀ k, approximationNumberPrefix k A ≤ approximationNumberPrefix k B) :
    A ∈ (generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .maximal)
      .toOperatorIdealFamily.carrier ∧
    generatedIdealGauge (𝕜 := 𝕜) Φ .maximal A ≤
      generatedIdealGauge (𝕜 := 𝕜) Φ .maximal B :=
  (generatedMaximalStandardIdeal (𝕜 := 𝕜) (v := v) Φ).fanDominance A B hB hprefix

/-- Fan dominance for the minimal ideal generated by any symmetric norming
function. -/
theorem generatedMinimal_fanDominance
    (Φ : SymmetricNormingFunction)
    {E F : Type v}
    [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
    [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]
    (A B : E →L[𝕜] F)
    (hB : B ∈ (generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .minimal)
      .toOperatorIdealFamily.carrier)
    (hprefix : ∀ k, approximationNumberPrefix k A ≤ approximationNumberPrefix k B) :
    A ∈ (generatedSymmetricIdealFamily (𝕜 := 𝕜) Φ .minimal)
      .toOperatorIdealFamily.carrier ∧
    generatedIdealGauge (𝕜 := 𝕜) Φ .minimal A ≤
      generatedIdealGauge (𝕜 := 𝕜) Φ .minimal B :=
  (generatedMinimalStandardIdeal (𝕜 := 𝕜) (v := v) Φ).fanDominance A B hB hprefix

end FinishTanTwoTheta
end TauCeti
