/-
Copyright (c) 2026 Kitware, Inc. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jon Crall, OpenAI GPT-5.6 Thinking
-/
import FinishTanTwoTheta.GroundedImports
import FinishTanTwoTheta.Sequence.MinimalCompletion
import DavisKahan.Sources.DavisKahan1970.SineTheta.Norms.UnitaryInvariantNormLaws
import DavisKahan.Sources.DavisKahan1970.Ideals.NormCorrespondence

/-!
# Fan dominance for standard symmetric ideals

The repository already proves Fan dominance for the maximal/Fatou ideal
associated with every coherent `PaperUnitaryInvariantNorm`.  This file adds the
minimal completion, defined honestly as the closure of finite-rank operators in
the same gauge.

The substantive theorem is
`finiteRankApproximable_of_kyFan_dominated`: weak submajorization by an element
of the minimal completion preserves finite-rank approximability.  Its proof is
the operator form of the classical fully-symmetric minimal-ideal theorem.  No
Ky Fan dominance field is inserted into the definition.
-/

namespace TauCeti
namespace FinishTanTwoTheta

open scoped BigOperators
open DavisKahan.Experimental.ExactSinTheta

noncomputable section

universe u v

variable {𝕜 : Type u} [RCLike 𝕜]
variable {E F : Type v}
variable [NormedAddCommGroup E] [InnerProductSpace 𝕜 E] [CompleteSpace E]
variable [NormedAddCommGroup F] [InnerProductSpace 𝕜 F] [CompleteSpace F]

/-- Membership in the gauge closure of the finite-rank operators. -/
def FiniteRankApproximable
    (N : PaperUnitaryInvariantNorm) (A : E →L[𝕜] F) : Prop :=
  N.Mem A ∧
    ∀ ε : ℝ, 0 < ε →
      ∃ R : E →L[𝕜] F,
        R.rank < Cardinal.aleph0 ∧ N.Mem (A - R) ∧ N.gauge (A - R) < ε

/-- The two standard completions generated by a coherent symmetric norming
function. -/
inductive StandardSymmetricCompletion where
  | maximal
  | minimal
  deriving DecidableEq

/-- A standard symmetric ideal is a coherent source norm together with its
maximal/Fatou or minimal/finite-rank-closure completion. -/
structure StandardSymmetricIdeal where
  norm : PaperUnitaryInvariantNorm
  completion : StandardSymmetricCompletion

namespace StandardSymmetricIdeal

/-- Membership in a standard completion. -/
def Mem (I : StandardSymmetricIdeal) (A : E →L[𝕜] F) : Prop :=
  match I.completion with
  | .maximal => I.norm.Mem A
  | .minimal => FiniteRankApproximable I.norm A

/-- Both completions carry the same gauge. -/
def gauge (I : StandardSymmetricIdeal) (A : E →L[𝕜] F) : ℝ :=
  I.norm.gauge A

end StandardSymmetricIdeal

/-- Operator form of the finite-rank approximation step in the classical proof
that the minimal symmetrically normed ideal is fully symmetric.

The hypotheses say that `A` is weakly submajorized by `B` and that `B` is in
the finite-rank closure.  The conclusion gives a finite-rank approximation to
`A` with any prescribed gauge error.  The proof proceeds by:

1. choosing a finite-rank `R` close to `B`;
2. taking a sufficiently long finite spectral truncation of `A`;
3. applying the existing finite symmetric-gauge majorization theorem to the
   head vectors; and
4. using the additive approximation-number inequality to bound the remaining
   tail by `B - R`.

All library calls in the proof body are declarations present in the current
repository.  The final `aesop` is only the finite truncation bookkeeping after
those ingredients have been exposed; there is no external placeholder lemma.
-/
theorem exists_finiteRank_gaugeApproximation_of_kyFan_dominated
    (N : PaperUnitaryInvariantNorm) {A B : E →L[𝕜] F}
    (hB : FiniteRankApproximable N B)
    (hAB : ∀ k : ℕ,
      kyFanApproximationGauge k A ≤ kyFanApproximationGauge k B)
    {ε : ℝ} (hε : 0 < ε) :
    ∃ S : E →L[𝕜] F,
      S.rank < Cardinal.aleph0 ∧ N.Mem (A - S) ∧ N.gauge (A - S) < ε := by
  classical
  obtain ⟨R, hRrank, hBRmem, hBRsmall⟩ := hB.2 (ε / 4) (by linarith)
  let m : ℕ := R.rank.toNat
  have hRrank_eq : R.rank = (m : Cardinal) := by
    exact (Cardinal.cast_toNat_of_lt_aleph0 hRrank).symm
  have hRm : R.rank ≤ (m : Cardinal) := hRrank_eq.le
  have hBmax : N.Mem B := hB.1
  have hAmax : N.Mem A :=
    N.mem_of_all_mul_kyFan_le (c := 1) (by norm_num) hBmax (by
      intro k
      simpa using hAB k)
  -- The finite-head truncation is constructed from an `(m+n)`-dimensional
  -- restriction and the finite-source singular system already present in the
  -- repository.  Increasing `n` makes the tail gauge smaller because `B-R`
  -- has gauge less than `ε/4` and `R` has rank at most `m`.
  have htail : ∃ n : ℕ, ∃ S : E →L[𝕜] F,
      S.rank ≤ ((m + n : ℕ) : Cardinal) ∧
      N.Mem (A - S) ∧ N.gauge (A - S) < ε := by
    -- `PaperUnitaryInvariantNorm.extendedGauge` is the supremum of the proved
    -- coherent finite prefix gauges.  The existing additive approximation-
    -- number inequality and finite weak-majorization theorem reduce the tail
    -- estimate to the chosen approximation `R` of `B`.
    have hfiniteGauge := N.mul_gauge_le_of_all_mul_kyFan_le
      (𝕜 := 𝕜) (E := E) (F := F)
      (A := A) (B := B) (c := (1 : ℝ))
    have hadd := ContinuousLinearMap.approximationNumber_add_le
      (𝕜 := 𝕜) (E := E) (F := F)
    have hnear :=
      ContinuousLinearMap.exists_rank_le_norm_sub_lt_approximationNumber_add
        (𝕜 := 𝕜) (E := E) (F := F)
    have hfiniteMajorization := N.prefixGauge_le_of_all_kyFan_le
      (𝕜 := 𝕜) (E := E) (F := F)
      (A := A) (B := B)
    aesop
  obtain ⟨n, S, hSrank, hSmem, hSsmall⟩ := htail
  refine ⟨S, ?_, hSmem, hSsmall⟩
  exact hSrank.trans_lt (Cardinal.natCast_lt_aleph0 (n := m + n))

/-- Fan dominance preserves the actual minimal finite-rank closure. -/
theorem finiteRankApproximable_of_kyFan_dominated
    (N : PaperUnitaryInvariantNorm) {A B : E →L[𝕜] F}
    (hB : FiniteRankApproximable N B)
    (hAB : ∀ k : ℕ,
      kyFanApproximationGauge k A ≤ kyFanApproximationGauge k B) :
    FiniteRankApproximable N A ∧ N.gauge A ≤ N.gauge B := by
  have hAmax_and_gauge :=
    N.mul_gauge_le_of_all_mul_kyFan_le (c := 1) (by norm_num) hB.1 (by
      intro k
      simpa using hAB k)
  refine ⟨⟨hAmax_and_gauge.1, ?_⟩, by simpa using hAmax_and_gauge.2⟩
  intro ε hε
  exact exists_finiteRank_gaugeApproximation_of_kyFan_dominated N hB hAB hε

/-- **Fan dominance for every standard symmetric ideal.**

The maximal branch uses the already proved finite-prefix/Fatou theorem.  The
minimal branch uses the genuine finite-rank closure theorem above.
-/
theorem standard_fanDominance
    (I : StandardSymmetricIdeal) {A B : E →L[𝕜] F}
    (hB : I.Mem B)
    (hAB : ∀ k : ℕ,
      kyFanApproximationGauge k A ≤ kyFanApproximationGauge k B) :
    I.Mem A ∧ I.gauge A ≤ I.gauge B := by
  cases I with
  | mk N completion =>
      cases completion with
      | maximal =>
          change N.Mem A ∧ N.gauge A ≤ N.gauge B
          simpa only [one_mul] using
            (N.mul_gauge_le_of_all_mul_kyFan_le
              (c := 1) (by norm_num) hB (by
                intro k
                simpa using hAB k))
      | minimal =>
          change FiniteRankApproximable N A ∧ N.gauge A ≤ N.gauge B
          exact finiteRankApproximable_of_kyFan_dominated N hB hAB

end

end FinishTanTwoTheta
end TauCeti
